// Generated by scripts/build-insforge-functions.cjs. DO NOT EDIT.

"use strict";
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// insforge-src/shared/http.js
var require_http = __commonJS({
  "insforge-src/shared/http.js"(exports2, module2) {
    "use strict";
    var corsHeaders = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey"
    };
    function handleOptions(request) {
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders });
      }
      return null;
    }
    function json(body, status = 200, extraHeaders = null) {
      return new Response(JSON.stringify(body), {
        status,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
          ...extraHeaders || {}
        }
      });
    }
    function requireMethod(request, method) {
      if (request.method !== method) return json({ error: "Method not allowed" }, 405);
      return null;
    }
    async function readJson(request) {
      if (!request.headers.get("Content-Type")?.includes("application/json")) {
        return { error: "Content-Type must be application/json", status: 415, data: null };
      }
      try {
        const data = await request.json();
        return { error: null, status: 200, data };
      } catch (_e) {
        return { error: "Invalid JSON", status: 400, data: null };
      }
    }
    module2.exports = {
      corsHeaders,
      handleOptions,
      json,
      requireMethod,
      readJson
    };
  }
});

// insforge-src/shared/logging.js
var require_logging = __commonJS({
  "insforge-src/shared/logging.js"(exports2, module2) {
    "use strict";
    function createRequestId() {
      if (globalThis?.crypto?.randomUUID) return globalThis.crypto.randomUUID();
      return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
    }
    function errorCodeFromStatus(status) {
      if (typeof status !== "number") return "UNKNOWN_ERROR";
      if (status >= 500) return "SERVER_ERROR";
      if (status >= 400) return "CLIENT_ERROR";
      return null;
    }
    function createLogger({ functionName }) {
      const requestId = createRequestId();
      const startMs = Date.now();
      let upstreamStatus = null;
      let upstreamLatencyMs = null;
      function recordUpstream(status, latencyMs) {
        upstreamStatus = typeof status === "number" ? status : null;
        upstreamLatencyMs = typeof latencyMs === "number" ? latencyMs : null;
      }
      async function fetchWithUpstream(url, init) {
        const upstreamStart = Date.now();
        try {
          const res = await fetch(url, init);
          recordUpstream(res.status, Date.now() - upstreamStart);
          return res;
        } catch (err) {
          recordUpstream(null, Date.now() - upstreamStart);
          throw err;
        }
      }
      function log({ stage, status, errorCode, ...extra }) {
        const payload = {
          ...extra || {},
          request_id: requestId,
          function: functionName,
          stage: stage || "response",
          status: typeof status === "number" ? status : null,
          latency_ms: Date.now() - startMs,
          error_code: errorCode ?? errorCodeFromStatus(status),
          upstream_status: upstreamStatus ?? null,
          upstream_latency_ms: upstreamLatencyMs ?? null
        };
        console.log(JSON.stringify(payload));
      }
      return {
        requestId,
        log,
        fetch: fetchWithUpstream
      };
    }
    function getResponseStatus(response) {
      if (response && typeof response.status === "number") return response.status;
      return null;
    }
    function resolveFunctionName(functionName, request) {
      if (request && typeof request.url === "string") {
        try {
          const url = new URL(request.url);
          const match = url.pathname.match(/\/functions\/([^/?#]+)/);
          if (match && match[1]) return match[1];
        } catch (_e) {
        }
      }
      return functionName;
    }
    function withRequestLogging(functionName, handler) {
      return async function(request) {
        const resolvedName = resolveFunctionName(functionName, request);
        const logger = createLogger({ functionName: resolvedName });
        try {
          const response = await handler(request, logger);
          const status = getResponseStatus(response);
          logger.log({ stage: "response", status });
          return response;
        } catch (err) {
          logger.log({ stage: "exception", status: 500, errorCode: "UNHANDLED_EXCEPTION" });
          throw err;
        }
      };
    }
    module2.exports = {
      withRequestLogging,
      logSlowQuery,
      getSlowQueryThresholdMs
    };
    function logSlowQuery(logger, fields) {
      if (!logger || typeof logger.log !== "function") return;
      const durationMs = Number(fields?.duration_ms ?? fields?.durationMs);
      if (!Number.isFinite(durationMs)) return;
      const thresholdMs = getSlowQueryThresholdMs();
      if (durationMs < thresholdMs) return;
      logger.log({
        stage: "slow_query",
        status: 200,
        ...fields || {},
        duration_ms: Math.round(durationMs)
      });
    }
    function getSlowQueryThresholdMs() {
      const raw = readEnvValue("VIBEUSAGE_SLOW_QUERY_MS") ?? readEnvValue("VIBESCORE_SLOW_QUERY_MS");
      if (raw == null || raw === "") return 2e3;
      const n = Number(raw);
      if (!Number.isFinite(n)) return 2e3;
      if (n <= 0) return 0;
      return clampInt(n, 1, 6e4);
    }
    function readEnvValue(key) {
      try {
        if (typeof Deno !== "undefined" && Deno?.env?.get) {
          const value = Deno.env.get(key);
          if (value !== void 0) return value;
        }
      } catch (_e) {
      }
      try {
        if (typeof process !== "undefined" && process?.env) {
          return process.env[key];
        }
      } catch (_e) {
      }
      return null;
    }
    function clampInt(value, min, max) {
      const n = Number(value);
      if (!Number.isFinite(n)) return min;
      return Math.min(max, Math.max(min, Math.floor(n)));
    }
  }
});

// insforge-src/shared/concurrency.js
var require_concurrency = __commonJS({
  "insforge-src/shared/concurrency.js"(exports2, module2) {
    "use strict";
    var LIMITERS = /* @__PURE__ */ new Map();
    function createConcurrencyGuard({
      name,
      envKey,
      defaultMax = 0,
      retryAfterEnvKey,
      defaultRetryAfterMs = 1e3
    }) {
      const maxInflight = readEnvInt(envKey, defaultMax);
      if (!Number.isFinite(maxInflight) || maxInflight <= 0) return null;
      const retryAfterMs = readEnvInt(retryAfterEnvKey, defaultRetryAfterMs);
      return getLimiter({ name, maxInflight, retryAfterMs });
    }
    function getLimiter({ name, maxInflight, retryAfterMs }) {
      const key = name || "default";
      const existing = LIMITERS.get(key);
      if (existing && existing.maxInflight === maxInflight && existing.retryAfterMs === retryAfterMs) return existing;
      const limiter = createLimiter({ maxInflight, retryAfterMs });
      LIMITERS.set(key, limiter);
      return limiter;
    }
    function createLimiter({ maxInflight, retryAfterMs }) {
      let inflight = 0;
      function acquire() {
        if (inflight >= maxInflight) {
          const retryAfterSeconds = Math.max(1, Math.ceil(Math.max(0, retryAfterMs) / 1e3));
          return {
            ok: false,
            retryAfterMs,
            headers: {
              "Retry-After": String(retryAfterSeconds)
            }
          };
        }
        inflight += 1;
        return {
          ok: true,
          release() {
            inflight = Math.max(0, inflight - 1);
          }
        };
      }
      return {
        maxInflight,
        retryAfterMs,
        acquire
      };
    }
    function readEnvInt(key, fallback) {
      if (!key) return fallback;
      const keys = Array.isArray(key) ? key : [key];
      for (const candidate of keys) {
        if (!candidate) continue;
        const raw = readEnvValue(candidate);
        if (raw == null || raw === "") continue;
        const n = Number(raw);
        if (!Number.isFinite(n)) continue;
        return Math.floor(n);
      }
      return fallback;
    }
    function readEnvValue(key) {
      try {
        if (typeof Deno !== "undefined" && Deno?.env?.get) {
          const value = Deno.env.get(key);
          if (value !== void 0) return value;
        }
      } catch (_e) {
      }
      try {
        if (typeof process !== "undefined" && process?.env) {
          return process.env[key];
        }
      } catch (_e) {
      }
      return null;
    }
    module2.exports = {
      createConcurrencyGuard
    };
  }
});

// insforge-src/shared/env.js
var require_env = __commonJS({
  "insforge-src/shared/env.js"(exports2, module2) {
    "use strict";
    function getBaseUrl() {
      return Deno.env.get("INSFORGE_INTERNAL_URL") || "http://insforge:7130";
    }
    function getServiceRoleKey() {
      return Deno.env.get("INSFORGE_SERVICE_ROLE_KEY") || Deno.env.get("SERVICE_ROLE_KEY") || Deno.env.get("INSFORGE_API_KEY") || Deno.env.get("API_KEY") || null;
    }
    function getAnonKey() {
      return Deno.env.get("ANON_KEY") || Deno.env.get("INSFORGE_ANON_KEY") || null;
    }
    module2.exports = {
      getBaseUrl,
      getServiceRoleKey,
      getAnonKey
    };
  }
});

// insforge-src/shared/auth.js
var require_auth = __commonJS({
  "insforge-src/shared/auth.js"(exports2, module2) {
    "use strict";
    var { getAnonKey } = require_env();
    function getBearerToken(headerValue) {
      if (!headerValue) return null;
      const prefix = "Bearer ";
      if (!headerValue.startsWith(prefix)) return null;
      const token = headerValue.slice(prefix.length).trim();
      return token.length > 0 ? token : null;
    }
    function decodeBase64Url(value) {
      if (typeof value !== "string") return null;
      let s = value.replace(/-/g, "+").replace(/_/g, "/");
      const pad = s.length % 4;
      if (pad) s += "=".repeat(4 - pad);
      try {
        if (typeof atob === "function") return atob(s);
      } catch (_e) {
      }
      try {
        if (typeof Buffer !== "undefined") {
          return Buffer.from(s, "base64").toString("utf8");
        }
      } catch (_e) {
      }
      return null;
    }
    function decodeJwtPayload(token) {
      if (typeof token !== "string") return null;
      const parts = token.split(".");
      if (parts.length < 2) return null;
      const raw = decodeBase64Url(parts[1]);
      if (!raw) return null;
      try {
        return JSON.parse(raw);
      } catch (_e) {
        return null;
      }
    }
    function getJwtRole(token) {
      const payload = decodeJwtPayload(token);
      const role = payload?.role;
      if (typeof role === "string" && role.length > 0) return role;
      const appRole = payload?.app_metadata?.role;
      if (typeof appRole === "string" && appRole.length > 0) return appRole;
      const roles = payload?.app_metadata?.roles;
      if (Array.isArray(roles)) {
        if (roles.includes("project_admin")) return "project_admin";
        const match = roles.find((value) => typeof value === "string" && value.length > 0);
        if (match) return match;
      }
      return null;
    }
    function isProjectAdminBearer(token) {
      const role = getJwtRole(token);
      return role === "project_admin";
    }
    function isJwtExpired(payload) {
      const exp = Number(payload?.exp);
      if (!Number.isFinite(exp)) return false;
      return exp * 1e3 <= Date.now();
    }
    async function getEdgeClientAndUserId({ baseUrl, bearer }) {
      const anonKey = getAnonKey();
      const edgeClient = createClient({ baseUrl, anonKey: anonKey || void 0, edgeFunctionToken: bearer });
      const { data: userData, error: userErr } = await edgeClient.auth.getCurrentUser();
      const userId = userData?.user?.id;
      if (userErr || !userId) return { ok: false, edgeClient: null, userId: null };
      return { ok: true, edgeClient, userId };
    }
    async function getEdgeClientAndUserIdFast({ baseUrl, bearer }) {
      const anonKey = getAnonKey();
      const edgeClient = createClient({ baseUrl, anonKey: anonKey || void 0, edgeFunctionToken: bearer });
      const payload = decodeJwtPayload(bearer);
      if (payload && isJwtExpired(payload)) {
        return { ok: false, edgeClient: null, userId: null };
      }
      const { data: userData, error: userErr } = await edgeClient.auth.getCurrentUser();
      const resolvedUserId = userData?.user?.id;
      if (userErr || !resolvedUserId) return { ok: false, edgeClient: null, userId: null };
      return { ok: true, edgeClient, userId: resolvedUserId };
    }
    module2.exports = {
      getBearerToken,
      getEdgeClientAndUserId,
      getEdgeClientAndUserIdFast,
      isProjectAdminBearer
    };
  }
});

// insforge-src/shared/crypto.js
var require_crypto = __commonJS({
  "insforge-src/shared/crypto.js"(exports2, module2) {
    "use strict";
    async function sha256Hex(input) {
      const data = new TextEncoder().encode(input);
      const hash = await crypto.subtle.digest("SHA-256", data);
      return Array.from(new Uint8Array(hash)).map((b) => b.toString(16).padStart(2, "0")).join("");
    }
    module2.exports = {
      sha256Hex
    };
  }
});

// insforge-src/shared/source.js
var require_source = __commonJS({
  "insforge-src/shared/source.js"(exports2, module2) {
    "use strict";
    var MAX_SOURCE_LENGTH = 64;
    function normalizeSource(value) {
      if (typeof value !== "string") return null;
      const normalized = value.trim().toLowerCase();
      if (!normalized) return null;
      if (normalized.length > MAX_SOURCE_LENGTH) return normalized.slice(0, MAX_SOURCE_LENGTH);
      return normalized;
    }
    function getSourceParam(url) {
      if (!url || typeof url.searchParams?.get !== "function") {
        return { ok: false, error: "Invalid request URL" };
      }
      const raw = url.searchParams.get("source");
      if (raw == null) return { ok: true, source: null };
      if (raw.trim() === "") return { ok: true, source: null };
      const normalized = normalizeSource(raw);
      if (!normalized) return { ok: false, error: "Invalid source" };
      return { ok: true, source: normalized };
    }
    module2.exports = {
      MAX_SOURCE_LENGTH,
      normalizeSource,
      getSourceParam
    };
  }
});

// insforge-src/shared/model.js
var require_model = __commonJS({
  "insforge-src/shared/model.js"(exports2, module2) {
    "use strict";
    function normalizeModel(value) {
      if (typeof value !== "string") return null;
      const trimmed = value.trim();
      return trimmed.length > 0 ? trimmed : null;
    }
    function getModelParam(url) {
      if (!url || typeof url.searchParams?.get !== "function") {
        return { ok: false, error: "Invalid request URL" };
      }
      const raw = url.searchParams.get("model");
      if (raw == null) return { ok: true, model: null };
      if (raw.trim() === "") return { ok: true, model: null };
      const normalized = normalizeModel(raw);
      if (!normalized) return { ok: false, error: "Invalid model" };
      return { ok: true, model: normalized };
    }
    module2.exports = {
      normalizeModel,
      getModelParam
    };
  }
});

// insforge-src/functions/vibescore-ingest.js
var require_vibescore_ingest = __commonJS({
  "insforge-src/functions/vibescore-ingest.js"(exports2, module2) {
    "use strict";
    var { handleOptions, json, requireMethod, readJson } = require_http();
    var { withRequestLogging } = require_logging();
    var { createConcurrencyGuard } = require_concurrency();
    var { getBearerToken } = require_auth();
    var { getAnonKey, getBaseUrl, getServiceRoleKey } = require_env();
    var { sha256Hex } = require_crypto();
    var { normalizeSource } = require_source();
    var { normalizeModel } = require_model();
    var MAX_BUCKETS = 500;
    var DEFAULT_MODEL = "unknown";
    var ingestGuard = createConcurrencyGuard({
      name: "vibescore-ingest",
      envKey: ["VIBEUSAGE_INGEST_MAX_INFLIGHT", "VIBESCORE_INGEST_MAX_INFLIGHT"],
      defaultMax: 0,
      retryAfterEnvKey: ["VIBEUSAGE_INGEST_RETRY_AFTER_MS", "VIBESCORE_INGEST_RETRY_AFTER_MS"],
      defaultRetryAfterMs: 1e3
    });
    module2.exports = withRequestLogging("vibescore-ingest", async function(request, logger) {
      const opt = handleOptions(request);
      if (opt) return opt;
      const methodErr = requireMethod(request, "POST");
      if (methodErr) return methodErr;
      const deviceToken = getBearerToken(request.headers.get("Authorization"));
      if (!deviceToken) return json({ error: "Missing bearer token" }, 401);
      const guard = ingestGuard?.acquire();
      if (guard && !guard.ok) {
        return json({ error: "Too many requests" }, 429, guard.headers);
      }
      const fetcher = logger?.fetch || fetch;
      const baseUrl = getBaseUrl();
      const serviceRoleKey = getServiceRoleKey();
      const anonKey = getAnonKey();
      const serviceClient = serviceRoleKey ? createClient({
        baseUrl,
        anonKey: anonKey || serviceRoleKey,
        edgeFunctionToken: serviceRoleKey
      }) : null;
      try {
        const tokenHash = await sha256Hex(deviceToken);
        let tokenRow = null;
        try {
          tokenRow = serviceClient ? await getTokenRowWithServiceClient(serviceClient, tokenHash) : await getTokenRowWithAnonKey({ baseUrl, anonKey, tokenHash, fetcher });
        } catch (e) {
          return json({ error: e?.message || "Internal error" }, 500);
        }
        if (!tokenRow) return json({ error: "Unauthorized" }, 401);
        const body = await readJson(request);
        if (body.error) return json({ error: body.error }, body.status);
        const hourly = normalizeHourly(body.data);
        if (!Array.isArray(hourly)) {
          return json({ error: "Invalid payload: expected {hourly:[...]} or [...]" }, 400);
        }
        if (hourly.length > MAX_BUCKETS) return json({ error: `Too many buckets (max ${MAX_BUCKETS})` }, 413);
        const nowIso = (/* @__PURE__ */ new Date()).toISOString();
        const rows = buildRows({ hourly, tokenRow, nowIso });
        if (rows.error) return json({ error: rows.error }, 400);
        if (rows.data.length === 0) {
          await recordIngestBatchMetrics({
            serviceClient,
            baseUrl,
            anonKey,
            tokenHash,
            tokenRow,
            bucketCount: 0,
            inserted: 0,
            skipped: 0,
            source: null,
            fetcher
          });
          return json({ success: true, inserted: 0, skipped: 0 }, 200);
        }
        const upsert = serviceClient ? await upsertWithServiceClient({
          serviceClient,
          tokenRow,
          rows: rows.data,
          nowIso,
          baseUrl,
          serviceRoleKey,
          tokenHash,
          fetcher
        }) : await upsertWithAnonKey({ baseUrl, anonKey, tokenHash, tokenRow, rows: rows.data, nowIso, fetcher });
        if (!upsert.ok) return json({ error: upsert.error }, 500);
        await recordIngestBatchMetrics({
          serviceClient,
          baseUrl,
          anonKey,
          tokenHash,
          tokenRow,
          bucketCount: rows.data.length,
          inserted: upsert.inserted,
          skipped: upsert.skipped,
          source: deriveMetricsSource(rows.data),
          fetcher
        });
        return json(
          {
            success: true,
            inserted: upsert.inserted,
            skipped: upsert.skipped
          },
          200
        );
      } finally {
        if (guard && typeof guard.release === "function") guard.release();
      }
    });
    function buildRows({ hourly, tokenRow, nowIso }) {
      const byHour = /* @__PURE__ */ new Map();
      for (const raw of hourly) {
        const parsed = parseHourlyBucket(raw);
        if (!parsed.ok) return { error: parsed.error, data: [] };
        const source = parsed.value.source || "codex";
        const model = parsed.value.model || DEFAULT_MODEL;
        const dedupeKey = `${parsed.value.hour_start}::${source}::${model}`;
        byHour.set(dedupeKey, { ...parsed.value, source, model });
      }
      const rows = [];
      for (const bucket of byHour.values()) {
        rows.push({
          user_id: tokenRow.user_id,
          device_id: tokenRow.device_id,
          device_token_id: tokenRow.id,
          source: bucket.source,
          model: bucket.model,
          hour_start: bucket.hour_start,
          input_tokens: bucket.input_tokens,
          cached_input_tokens: bucket.cached_input_tokens,
          output_tokens: bucket.output_tokens,
          reasoning_output_tokens: bucket.reasoning_output_tokens,
          total_tokens: bucket.total_tokens,
          updated_at: nowIso
        });
      }
      return { error: null, data: rows };
    }
    function deriveMetricsSource(rows) {
      if (!Array.isArray(rows) || rows.length === 0) return null;
      const sources = /* @__PURE__ */ new Set();
      for (const row of rows) {
        const source = typeof row?.source === "string" ? row.source.trim() : "";
        if (source) sources.add(source);
      }
      if (sources.size === 1) return Array.from(sources)[0];
      if (sources.size > 1) return "mixed";
      return null;
    }
    async function getTokenRowWithServiceClient(serviceClient, tokenHash) {
      const { data: tokenRow, error: tokenErr } = await serviceClient.database.from("vibescore_tracker_device_tokens").select("id,user_id,device_id,revoked_at,last_sync_at").eq("token_hash", tokenHash).maybeSingle();
      if (tokenErr) throw new Error(tokenErr.message);
      if (!tokenRow || tokenRow.revoked_at) return null;
      return tokenRow;
    }
    async function getTokenRowWithAnonKey({ baseUrl, anonKey, tokenHash, fetcher }) {
      if (!anonKey) throw new Error("Anon key missing");
      const url = new URL("/api/database/records/vibescore_tracker_device_tokens", baseUrl);
      url.searchParams.set("select", "id,user_id,device_id,revoked_at,last_sync_at");
      url.searchParams.set("token_hash", `eq.${tokenHash}`);
      url.searchParams.set("limit", "1");
      const res = await (fetcher || fetch)(url.toString(), {
        method: "GET",
        headers: buildAnonHeaders({ anonKey, tokenHash })
      });
      const { data, error } = await readApiJson(res);
      if (!res.ok) throw new Error(error || `HTTP ${res.status}`);
      const rows = normalizeRows(data);
      const tokenRow = rows?.[0] || null;
      if (!tokenRow || tokenRow.revoked_at) return null;
      return tokenRow;
    }
    async function upsertWithServiceClient({
      serviceClient,
      tokenRow,
      rows,
      nowIso,
      baseUrl,
      serviceRoleKey,
      tokenHash,
      fetcher
    }) {
      if (serviceRoleKey && baseUrl) {
        const url = new URL("/api/database/records/vibescore_tracker_hourly", baseUrl);
        const res = await recordsUpsert({
          url,
          anonKey: serviceRoleKey,
          tokenHash,
          rows,
          onConflict: "user_id,device_id,source,model,hour_start",
          prefer: "return=representation",
          resolution: "merge-duplicates",
          select: "hour_start",
          fetcher
        });
        if (res.ok) {
          const insertedRows = normalizeRows(res.data);
          const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
          await bestEffortTouchWithServiceClient(serviceClient, tokenRow, nowIso);
          return { ok: true, inserted, skipped: 0 };
        }
        if (!isUpsertUnsupported(res)) {
          return { ok: false, error: res.error || `HTTP ${res.status}`, inserted: 0, skipped: 0 };
        }
      }
      const table = serviceClient.database.from("vibescore_tracker_hourly");
      if (typeof table?.upsert === "function") {
        const { error } = await table.upsert(rows, { onConflict: "user_id,device_id,source,model,hour_start" });
        if (error) return { ok: false, error: error.message, inserted: 0, skipped: 0 };
        await bestEffortTouchWithServiceClient(serviceClient, tokenRow, nowIso);
        return { ok: true, inserted: rows.length, skipped: 0 };
      }
      return { ok: false, error: "Half-hour upsert unsupported", inserted: 0, skipped: 0 };
    }
    async function upsertWithAnonKey({ baseUrl, anonKey, tokenHash, tokenRow, rows, nowIso, fetcher }) {
      if (!anonKey) return { ok: false, error: "Anon key missing", inserted: 0, skipped: 0 };
      const url = new URL("/api/database/records/vibescore_tracker_hourly", baseUrl);
      const res = await recordsUpsert({
        url,
        anonKey,
        tokenHash,
        rows,
        onConflict: "user_id,device_id,source,model,hour_start",
        prefer: "return=representation",
        resolution: "merge-duplicates",
        select: "hour_start",
        fetcher
      });
      if (res.ok) {
        const insertedRows = normalizeRows(res.data);
        const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
        await bestEffortTouchWithAnonKey({ baseUrl, anonKey, tokenHash, fetcher });
        return { ok: true, inserted, skipped: 0 };
      }
      if (isUpsertUnsupported(res)) {
        return { ok: false, error: res.error || "Half-hour upsert unsupported", inserted: 0, skipped: 0 };
      }
      return { ok: false, error: res.error || `HTTP ${res.status}`, inserted: 0, skipped: 0 };
    }
    async function recordIngestBatchMetrics({
      serviceClient,
      baseUrl,
      anonKey,
      tokenHash,
      tokenRow,
      bucketCount,
      inserted,
      skipped,
      source,
      fetcher
    }) {
      if (!tokenRow) return;
      const row = {
        user_id: tokenRow.user_id,
        device_id: tokenRow.device_id,
        device_token_id: tokenRow.id,
        source: typeof source === "string" ? source : null,
        bucket_count: toNonNegativeInt(bucketCount) ?? 0,
        inserted: toNonNegativeInt(inserted) ?? 0,
        skipped: toNonNegativeInt(skipped) ?? 0
      };
      try {
        if (serviceClient) {
          const { error } = await serviceClient.database.from("vibescore_tracker_ingest_batches").insert(row);
          if (error) throw new Error(error.message);
          return;
        }
        if (!anonKey || !baseUrl) return;
        const url = new URL("/api/database/records/vibescore_tracker_ingest_batches", baseUrl);
        const res = await (fetcher || fetch)(url.toString(), {
          method: "POST",
          headers: {
            ...buildAnonHeaders({ anonKey, tokenHash }),
            "Content-Type": "application/json"
          },
          body: JSON.stringify(row)
        });
        if (!res.ok) {
          const { error } = await readApiJson(res);
          throw new Error(error || `HTTP ${res.status}`);
        }
      } catch (_e) {
      }
    }
    async function bestEffortTouchWithServiceClient(serviceClient, tokenRow, nowIso) {
      const lastSyncAt = normalizeIso(tokenRow?.last_sync_at);
      const shouldUpdateSync = !lastSyncAt || !isWithinInterval(lastSyncAt, 30);
      try {
        await serviceClient.database.from("vibescore_tracker_device_tokens").update(shouldUpdateSync ? { last_used_at: nowIso, last_sync_at: nowIso } : { last_used_at: nowIso }).eq("id", tokenRow.id);
      } catch (_e) {
      }
      try {
        await serviceClient.database.from("vibescore_tracker_devices").update({ last_seen_at: nowIso }).eq("id", tokenRow.device_id);
      } catch (_e) {
      }
    }
    async function bestEffortTouchWithAnonKey({ baseUrl, anonKey, tokenHash, fetcher }) {
      if (!anonKey) return;
      try {
        const url = new URL("/api/database/rpc/vibescore_touch_device_token_sync", baseUrl);
        await (fetcher || fetch)(url.toString(), {
          method: "POST",
          headers: {
            ...buildAnonHeaders({ anonKey, tokenHash }),
            "Content-Type": "application/json"
          },
          body: JSON.stringify({ min_interval_minutes: 30 })
        });
      } catch (_e) {
      }
    }
    function buildAnonHeaders({ anonKey, tokenHash }) {
      return {
        apikey: anonKey,
        Authorization: `Bearer ${anonKey}`,
        "x-vibeusage-device-token-hash": tokenHash
      };
    }
    async function recordsUpsert({ url, anonKey, tokenHash, rows, onConflict, prefer, resolution, select, fetcher }) {
      const target = new URL(url.toString());
      if (onConflict) target.searchParams.set("on_conflict", onConflict);
      if (select) target.searchParams.set("select", select);
      const preferParts = [];
      if (prefer) preferParts.push(prefer);
      if (resolution) preferParts.push(`resolution=${resolution}`);
      const preferHeader = preferParts.filter(Boolean).join(",");
      const res = await (fetcher || fetch)(target.toString(), {
        method: "POST",
        headers: {
          ...buildAnonHeaders({ anonKey, tokenHash }),
          ...preferHeader ? { Prefer: preferHeader } : {},
          "Content-Type": "application/json"
        },
        body: JSON.stringify(rows)
      });
      const { data, error, code } = await readApiJson(res);
      return { ok: res.ok, status: res.status, data, error, code };
    }
    async function readApiJson(res) {
      const text = await res.text();
      if (!text) return { data: null, error: null, code: null };
      try {
        const parsed = JSON.parse(text);
        return { data: parsed, error: parsed?.message || parsed?.error || null, code: parsed?.code || null };
      } catch (_e) {
        return { data: null, error: text.slice(0, 300), code: null };
      }
    }
    function normalizeRows(data) {
      if (Array.isArray(data)) return data;
      if (data && typeof data === "object" && Array.isArray(data.data)) return data.data;
      return null;
    }
    function normalizeIso(value) {
      if (typeof value !== "string") return null;
      const dt = new Date(value);
      if (!Number.isFinite(dt.getTime())) return null;
      return dt.toISOString();
    }
    function isWithinInterval(lastSyncAt, minutes) {
      const lastMs = Date.parse(lastSyncAt);
      if (!Number.isFinite(lastMs)) return false;
      const windowMs = Math.max(0, minutes) * 60 * 1e3;
      return windowMs > 0 && Date.now() - lastMs < windowMs;
    }
    function isUpsertUnsupported(result) {
      const status = Number(result?.status || 0);
      if (status !== 400 && status !== 404 && status !== 405 && status !== 409 && status !== 422) return false;
      const msg = String(result?.error || "").toLowerCase();
      if (!msg) return false;
      return msg.includes("on_conflict") || msg.includes("resolution") || msg.includes("prefer") || msg.includes("unknown") || msg.includes("invalid");
    }
    function normalizeHourly(data) {
      if (Array.isArray(data)) return data;
      if (data && typeof data === "object") {
        if (Array.isArray(data.hourly)) return data.hourly;
        if (Array.isArray(data.data)) return data.data;
        if (data.data && typeof data.data === "object" && Array.isArray(data.data.hourly)) {
          return data.data.hourly;
        }
      }
      return null;
    }
    function parseHourlyBucket(raw) {
      if (!raw || typeof raw !== "object") return { ok: false, error: "Invalid half-hour bucket" };
      const hourStart = parseUtcHalfHourStart(raw.hour_start);
      if (!hourStart) {
        return { ok: false, error: "hour_start must be an ISO timestamp at UTC half-hour boundary" };
      }
      const source = normalizeSource(raw.source);
      const model = normalizeModel(raw.model) || DEFAULT_MODEL;
      const input = toNonNegativeInt(raw.input_tokens);
      const cached = toNonNegativeInt(raw.cached_input_tokens);
      const output = toNonNegativeInt(raw.output_tokens);
      const reasoning = toNonNegativeInt(raw.reasoning_output_tokens);
      const total = toNonNegativeInt(raw.total_tokens);
      if ([input, cached, output, reasoning, total].some((n) => n == null)) {
        return { ok: false, error: "Token fields must be non-negative integers" };
      }
      return {
        ok: true,
        value: {
          source,
          model,
          hour_start: hourStart,
          input_tokens: input,
          cached_input_tokens: cached,
          output_tokens: output,
          reasoning_output_tokens: reasoning,
          total_tokens: total
        }
      };
    }
    function parseUtcHalfHourStart(value) {
      if (typeof value !== "string" || value.trim() === "") return null;
      const dt = new Date(value);
      if (!Number.isFinite(dt.getTime())) return null;
      const minutes = dt.getUTCMinutes();
      if (minutes !== 0 && minutes !== 30 || dt.getUTCSeconds() !== 0 || dt.getUTCMilliseconds() !== 0) {
        return null;
      }
      const hourStart = new Date(
        Date.UTC(
          dt.getUTCFullYear(),
          dt.getUTCMonth(),
          dt.getUTCDate(),
          dt.getUTCHours(),
          minutes >= 30 ? 30 : 0,
          0,
          0
        )
      );
      return hourStart.toISOString();
    }
    function toNonNegativeInt(n) {
      if (typeof n !== "number") return null;
      if (!Number.isFinite(n)) return null;
      if (!Number.isInteger(n)) return null;
      if (n < 0) return null;
      return n;
    }
  }
});

// insforge-src/functions/vibeusage-ingest.js
module.exports = require_vibescore_ingest();
