// @ts-nocheck
import { createClient as __insforgeCreateClient } from "npm:@insforge/sdk";
if (typeof globalThis.createClient !== "function") globalThis.createClient = __insforgeCreateClient;
// Generated by scripts/build-insforge-functions.cjs. DO NOT EDIT.


// insforge-src/shared/auth-core.mjs
var CORE_KEY = "__vibeusageAuthCore";
function getBearerToken(headerValue) {
  if (!headerValue) return null;
  const prefix = "Bearer ";
  if (!headerValue.startsWith(prefix)) return null;
  const token = headerValue.slice(prefix.length).trim();
  return token.length > 0 ? token : null;
}
function decodeBase64Url(value) {
  if (typeof value !== "string") return null;
  let normalized = value.replace(/-/g, "+").replace(/_/g, "/");
  const pad = normalized.length % 4;
  if (pad) normalized += "=".repeat(4 - pad);
  try {
    if (typeof atob === "function") return atob(normalized);
  } catch (_error) {
  }
  try {
    if (typeof Buffer !== "undefined") {
      return Buffer.from(normalized, "base64").toString("utf8");
    }
  } catch (_error) {
  }
  return null;
}
function decodeJwtSection(token, index) {
  if (typeof token !== "string") return null;
  const parts = token.split(".");
  if (parts.length < index + 1) return null;
  const raw = decodeBase64Url(parts[index]);
  if (!raw) return null;
  try {
    return JSON.parse(raw);
  } catch (_error) {
    return null;
  }
}
function decodeJwtPayload(token) {
  return decodeJwtSection(token, 1);
}
function decodeJwtHeader(token) {
  return decodeJwtSection(token, 0);
}
function getJwtRole(token) {
  const payload = decodeJwtPayload(token);
  const role = payload?.role;
  if (typeof role === "string" && role.length > 0) return role;
  const appRole = payload?.app_metadata?.role;
  if (typeof appRole === "string" && appRole.length > 0) return appRole;
  const roles = payload?.app_metadata?.roles;
  if (Array.isArray(roles)) {
    if (roles.includes("project_admin")) return "project_admin";
    const match = roles.find((value) => typeof value === "string" && value.length > 0);
    if (match) return match;
  }
  return null;
}
function isProjectAdminBearer(token) {
  return getJwtRole(token) === "project_admin";
}
function isJwtExpired(payload) {
  const exp = Number(payload?.exp);
  if (!Number.isFinite(exp)) return false;
  return exp * 1e3 <= Date.now();
}
function base64UrlEncode(value) {
  let base64 = null;
  try {
    if (typeof Buffer !== "undefined") {
      base64 = Buffer.from(value).toString("base64");
    }
  } catch (_error) {
  }
  if (!base64 && typeof btoa === "function" && value instanceof ArrayBuffer) {
    const bytes = new Uint8Array(value);
    let binary = "";
    for (const byte of bytes) binary += String.fromCharCode(byte);
    base64 = btoa(binary);
  }
  if (!base64) return null;
  return base64.replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}
async function verifyUserJwtHs256({ token, jwtSecret }) {
  const secret = typeof jwtSecret === "string" && jwtSecret.length > 0 ? jwtSecret : null;
  if (!secret) {
    return { ok: false, userId: null, error: "Missing jwt secret", code: "missing_jwt_secret" };
  }
  if (typeof token !== "string") return { ok: false, userId: null, error: "Invalid token" };
  const parts = token.split(".");
  if (parts.length !== 3) return { ok: false, userId: null, error: "Invalid token" };
  const header = decodeJwtHeader(token);
  if (!header || header.alg !== "HS256") {
    return { ok: false, userId: null, error: "Unsupported alg" };
  }
  const payload = decodeJwtPayload(token);
  if (!payload) return { ok: false, userId: null, error: "Invalid payload" };
  const exp = Number(payload?.exp);
  if (!Number.isFinite(exp)) return { ok: false, userId: null, error: "Missing exp" };
  if (isJwtExpired(payload)) return { ok: false, userId: null, error: "Token expired" };
  const cryptoSubtle = globalThis.crypto?.subtle;
  if (!cryptoSubtle) return { ok: false, userId: null, error: "Crypto unavailable" };
  const data = `${parts[0]}.${parts[1]}`;
  const encoder = new TextEncoder();
  const key = await cryptoSubtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await cryptoSubtle.sign("HMAC", key, encoder.encode(data));
  const expected = base64UrlEncode(signature);
  if (!expected || expected !== parts[2]) {
    return { ok: false, userId: null, error: "Invalid signature" };
  }
  const userId = typeof payload.sub === "string" ? payload.sub : null;
  if (!userId) return { ok: false, userId: null, error: "Missing sub" };
  return { ok: true, userId, error: null };
}
function getClaimedJwtUser({ token }) {
  const header = decodeJwtHeader(token);
  if (!header || header.alg !== "HS256") {
    return { ok: false, userId: null, code: "invalid_jwt" };
  }
  const payload = decodeJwtPayload(token);
  if (!payload || isJwtExpired(payload)) {
    return { ok: false, userId: null, code: "invalid_jwt" };
  }
  const userId = typeof payload.sub === "string" ? payload.sub : null;
  if (!userId) return { ok: false, userId: null, code: "invalid_jwt" };
  return { ok: true, userId, code: null };
}
async function getEdgeClientAndUserIdFast({
  baseUrl,
  bearer,
  createUserEdgeClient,
  jwtSecret
} = {}) {
  const edgeClient = typeof createUserEdgeClient === "function" ? await createUserEdgeClient({ baseUrl, bearer }) : null;
  const local = await verifyUserJwtHs256({ token: bearer, jwtSecret });
  if (local.ok) {
    return { ok: true, edgeClient, userId: local.userId };
  }
  if (local?.code !== "missing_jwt_secret") {
    return {
      ok: false,
      edgeClient: null,
      userId: null,
      status: 401,
      error: "Unauthorized",
      code: local?.code || "invalid_jwt"
    };
  }
  const claimed = getClaimedJwtUser({ token: bearer });
  if (!claimed.ok) {
    return {
      ok: false,
      edgeClient: null,
      userId: null,
      status: 401,
      error: "Unauthorized",
      code: claimed.code || "invalid_jwt"
    };
  }
  return { ok: true, edgeClient, userId: claimed.userId };
}
async function getEdgeClientAndUserId({
  baseUrl,
  bearer,
  createUserEdgeClient,
  jwtSecret
} = {}) {
  const auth = await getEdgeClientAndUserIdFast({
    baseUrl,
    bearer,
    createUserEdgeClient,
    jwtSecret
  });
  if (!auth.ok) {
    return {
      ok: false,
      edgeClient: null,
      userId: null,
      status: auth.status ?? 401,
      error: auth.error ?? "Unauthorized",
      code: auth.code ?? null
    };
  }
  return { ok: true, edgeClient: auth.edgeClient, userId: auth.userId };
}
async function getAccessContext({
  baseUrl,
  bearer,
  allowPublic = false,
  createUserEdgeClient,
  jwtSecret,
  isPublicShareToken: isPublicShareToken3,
  resolvePublicView: resolvePublicView3
} = {}) {
  if (!bearer) {
    return {
      ok: false,
      edgeClient: null,
      userId: null,
      accessType: null,
      status: 401,
      error: "Unauthorized",
      code: "missing_bearer"
    };
  }
  const auth = await getEdgeClientAndUserIdFast({
    baseUrl,
    bearer,
    createUserEdgeClient,
    jwtSecret
  });
  if (auth.ok) {
    return { ok: true, edgeClient: auth.edgeClient, userId: auth.userId, accessType: "user" };
  }
  if (!allowPublic) {
    return {
      ok: false,
      edgeClient: null,
      userId: null,
      accessType: null,
      status: auth.status ?? 401,
      error: auth.error ?? "Unauthorized",
      code: auth.code ?? null
    };
  }
  if (typeof isPublicShareToken3 !== "function" || !isPublicShareToken3(bearer)) {
    return {
      ok: false,
      edgeClient: null,
      userId: null,
      accessType: null,
      status: auth.status ?? 401,
      error: auth.error ?? "Unauthorized",
      code: auth.code ?? null
    };
  }
  const publicView = typeof resolvePublicView3 === "function" ? await resolvePublicView3({ baseUrl, shareToken: bearer }) : null;
  if (!publicView?.ok) {
    return {
      ok: false,
      edgeClient: null,
      userId: null,
      accessType: null,
      status: 401,
      error: "Unauthorized"
    };
  }
  return {
    ok: true,
    edgeClient: publicView.edgeClient,
    userId: publicView.userId,
    accessType: "public"
  };
}
if (!globalThis[CORE_KEY]) {
  Object.defineProperty(globalThis, CORE_KEY, {
    value: {
      getBearerToken,
      isProjectAdminBearer,
      verifyUserJwtHs256,
      getEdgeClientAndUserIdFast,
      getEdgeClientAndUserId,
      getAccessContext
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/shared/runtime-primitives-core.mjs
var CORE_KEY2 = "__vibeusageRuntimePrimitivesCore";
var MAX_SOURCE_LENGTH = 64;
function toBigInt(value) {
  if (typeof value === "bigint") return value >= 0n ? value : 0n;
  if (typeof value === "number") {
    if (!Number.isFinite(value) || value <= 0) return 0n;
    return BigInt(Math.floor(value));
  }
  if (typeof value === "string") {
    const trimmed = value.trim();
    if (!/^[0-9]+$/.test(trimmed)) return 0n;
    try {
      return BigInt(trimmed);
    } catch (_error) {
      return 0n;
    }
  }
  return 0n;
}
function toPositiveIntOrNull(value) {
  if (typeof value === "number" && Number.isInteger(value) && value > 0) return value;
  if (typeof value === "string") {
    const trimmed = value.trim();
    if (!/^[0-9]+$/.test(trimmed)) return null;
    const n = Number.parseInt(trimmed, 10);
    return Number.isFinite(n) && n > 0 ? n : null;
  }
  if (typeof value === "bigint") {
    if (value <= 0n) return null;
    const n = Number(value);
    return Number.isFinite(n) && n > 0 ? n : null;
  }
  return null;
}
function toPositiveInt(value) {
  const n = toPositiveIntOrNull(value);
  return n == null ? 0 : n;
}
function normalizeSource(value) {
  if (typeof value !== "string") return null;
  const normalized = value.trim().toLowerCase();
  if (!normalized) return null;
  if (normalized.length > MAX_SOURCE_LENGTH) return normalized.slice(0, MAX_SOURCE_LENGTH);
  return normalized;
}
function getSourceParam(url) {
  if (!url || typeof url.searchParams?.get !== "function") {
    return { ok: false, error: "Invalid request URL" };
  }
  const raw = url.searchParams.get("source");
  if (raw == null) return { ok: true, source: null };
  if (raw.trim() === "") return { ok: true, source: null };
  const normalized = normalizeSource(raw);
  if (!normalized) return { ok: false, error: "Invalid source" };
  return { ok: true, source: normalized };
}
if (!globalThis[CORE_KEY2]) {
  Object.defineProperty(globalThis, CORE_KEY2, {
    value: {
      MAX_SOURCE_LENGTH,
      toBigInt,
      toPositiveInt,
      toPositiveIntOrNull,
      normalizeSource,
      getSourceParam
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/shared/usage-model-core.mjs
var CORE_KEY3 = "__vibeusageUsageModelCore";
var DEFAULT_MODEL = "unknown";
function normalizeModel(value) {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}
function normalizeUsageModel(value) {
  const normalized = normalizeModel(value);
  return normalized ? normalized.toLowerCase() : null;
}
function escapeLike(value) {
  return String(value).replace(/[\\%_]/g, "\\$&");
}
function applyUsageModelFilter(query, usageModels) {
  if (!query || typeof query.or !== "function") return query;
  const models = Array.isArray(usageModels) ? usageModels : [];
  const terms = [];
  const seen = /* @__PURE__ */ new Set();
  for (const model of models) {
    const normalized = normalizeUsageModel(model);
    if (!normalized) continue;
    const exact = `model.ilike.${escapeLike(normalized)}`;
    if (seen.has(exact)) continue;
    seen.add(exact);
    terms.push(exact);
  }
  if (terms.length === 0) return query;
  return query.or(terms.join(","));
}
function getModelParam(url) {
  if (!url || typeof url.searchParams?.get !== "function") {
    return { ok: false, error: "Invalid request URL" };
  }
  const raw = url.searchParams.get("model");
  if (raw == null || raw.trim() === "") return { ok: true, model: null };
  const normalized = normalizeUsageModel(raw);
  if (!normalized) return { ok: false, error: "Invalid model" };
  return { ok: true, model: normalized };
}
function normalizeDateKey(value) {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  return trimmed.length >= 10 ? trimmed.slice(0, 10) : trimmed;
}
function extractDateKey(value) {
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  if (typeof value === "string" && value.length >= 10) return value.slice(0, 10);
  return null;
}
function nextDateKey(dateKey) {
  if (!dateKey) return null;
  const date = /* @__PURE__ */ new Date(`${dateKey}T00:00:00Z`);
  if (Number.isNaN(date.getTime())) return null;
  date.setUTCDate(date.getUTCDate() + 1);
  return date.toISOString().slice(0, 10);
}
function normalizeUsageModelKey(value) {
  return normalizeUsageModel(value);
}
function normalizeDisplayNameValue(value) {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed || null;
}
function buildIdentityMap({ usageModels, aliasRows } = {}) {
  const normalized = /* @__PURE__ */ new Set();
  for (const model of Array.isArray(usageModels) ? usageModels : []) {
    const key = normalizeUsageModelKey(model);
    if (key) normalized.add(key);
  }
  const map = /* @__PURE__ */ new Map();
  for (const row of Array.isArray(aliasRows) ? aliasRows : []) {
    const usageKey = normalizeUsageModelKey(row?.usage_model);
    const canonical = normalizeUsageModelKey(row?.canonical_model);
    if (!usageKey || !canonical) continue;
    if (normalized.size > 0 && !normalized.has(usageKey)) continue;
    const display = normalizeDisplayNameValue(row?.display_name) || canonical;
    const effective = String(row?.effective_from || "");
    const existing = map.get(usageKey);
    if (!existing || effective > existing.effective_from) {
      map.set(usageKey, { model_id: canonical, model: display, effective_from: effective });
    }
  }
  for (const key of normalized) {
    if (!map.has(key)) {
      map.set(key, { model_id: key, model: key, effective_from: "" });
    }
  }
  const result = /* @__PURE__ */ new Map();
  for (const [key, value] of map.entries()) {
    result.set(key, { model_id: value.model_id, model: value.model });
  }
  return result;
}
function applyModelIdentity({ rawModel, identityMap } = {}) {
  const normalized = normalizeUsageModelKey(rawModel) || DEFAULT_MODEL;
  const entry = identityMap && typeof identityMap.get === "function" ? identityMap.get(normalized) : null;
  if (entry) return { model_id: entry.model_id, model: entry.model };
  const display = normalizeDisplayNameValue(rawModel) || DEFAULT_MODEL;
  return { model_id: normalized, model: display };
}
function readQueryOutcome(result, query) {
  const data = Array.isArray(result?.data) ? result.data : Array.isArray(query?.data) ? query.data : null;
  const error = result?.error || query?.error || null;
  return { data, error };
}
async function resolveModelIdentity({ edgeClient, usageModels, effectiveDate } = {}) {
  const models = Array.isArray(usageModels) ? usageModels.map(normalizeUsageModelKey).filter(Boolean) : [];
  if (!models.length) return /* @__PURE__ */ new Map();
  const database = edgeClient?.database;
  if (!database || typeof database.from !== "function") {
    return buildIdentityMap({ usageModels: models, aliasRows: [] });
  }
  const dateKey = normalizeDateKey(effectiveDate) || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  const dateKeyNext = nextDateKey(dateKey) || dateKey;
  const query = database.from("vibeusage_model_aliases").select("usage_model,canonical_model,display_name,effective_from");
  if (!query || typeof query.eq !== "function" || typeof query.in !== "function" || typeof query.lt !== "function" || typeof query.order !== "function") {
    return buildIdentityMap({ usageModels: models, aliasRows: [] });
  }
  const result = await query.eq("active", true).in("usage_model", models).lt("effective_from", dateKeyNext).order("effective_from", { ascending: false });
  const { data, error } = readQueryOutcome(result, query);
  if (error || !Array.isArray(data)) {
    return buildIdentityMap({ usageModels: models, aliasRows: [] });
  }
  return buildIdentityMap({ usageModels: models, aliasRows: data });
}
async function resolveUsageModelsForCanonical({ edgeClient, canonicalModel, effectiveDate } = {}) {
  const canonical = normalizeUsageModelKey(canonicalModel);
  if (!canonical) return { canonical: null, usageModels: [] };
  const database = edgeClient?.database;
  if (!database || typeof database.from !== "function") {
    return { canonical, usageModels: [canonical] };
  }
  const dateKey = normalizeDateKey(effectiveDate) || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  const dateKeyNext = nextDateKey(dateKey) || dateKey;
  const query = database.from("vibeusage_model_aliases").select("usage_model,canonical_model,effective_from");
  if (!query || typeof query.eq !== "function" || typeof query.lt !== "function" || typeof query.order !== "function") {
    return { canonical, usageModels: [canonical] };
  }
  const result = await query.eq("active", true).eq("canonical_model", canonical).lt("effective_from", dateKeyNext).order("effective_from", { ascending: false });
  const { data, error } = readQueryOutcome(result, query);
  if (error || !Array.isArray(data)) {
    return { canonical, usageModels: [canonical] };
  }
  const usageMap = /* @__PURE__ */ new Map();
  for (const row of data) {
    const usageKey = normalizeUsageModelKey(row?.usage_model);
    if (!usageKey) continue;
    const effective = String(row?.effective_from || "");
    const existing = usageMap.get(usageKey);
    if (!existing || effective > existing) usageMap.set(usageKey, effective);
  }
  const usageModelsSet = /* @__PURE__ */ new Set([canonical]);
  for (const usageKey of usageMap.keys()) {
    usageModelsSet.add(usageKey);
  }
  return { canonical, usageModels: Array.from(usageModelsSet.values()) };
}
async function resolveUsageFilterContext({ edgeClient, canonicalModel, effectiveDate } = {}) {
  const modelFilter = await resolveUsageModelsForCanonical({
    edgeClient,
    canonicalModel,
    effectiveDate
  });
  const resolvedCanonicalModel = modelFilter.canonical;
  const timelineContext = await resolveUsageTimelineContext({
    edgeClient,
    usageModels: modelFilter.usageModels,
    effectiveDate
  });
  const usageModels = timelineContext.usageModels;
  const hasModelFilter = usageModels.length > 0;
  if (!hasModelFilter) {
    return {
      canonicalModel: resolvedCanonicalModel,
      usageModels,
      hasModelFilter,
      aliasTimeline: null
    };
  }
  return {
    canonicalModel: resolvedCanonicalModel,
    usageModels,
    hasModelFilter,
    aliasTimeline: timelineContext.aliasTimeline
  };
}
async function resolveUsageTimelineContext({ edgeClient, usageModels, effectiveDate } = {}) {
  const normalizedUsageModels = Array.isArray(usageModels) ? usageModels.map((model) => normalizeUsageModelKey(model)).filter(Boolean) : [];
  if (!normalizedUsageModels.length) {
    return {
      usageModels: [],
      aliasTimeline: null
    };
  }
  const aliasRows = await fetchAliasRows({
    edgeClient,
    usageModels: normalizedUsageModels,
    effectiveDate
  });
  return {
    usageModels: normalizedUsageModels,
    aliasTimeline: buildAliasTimeline({
      usageModels: normalizedUsageModels,
      aliasRows
    })
  };
}
function resolveIdentityAtDate({ rawModel, usageKey, dateKey, timeline } = {}) {
  const normalizedKey = usageKey || normalizeUsageModelKey(rawModel) || DEFAULT_MODEL;
  const normalizedDateKey = extractDateKey(dateKey) || dateKey || null;
  const entries = timeline && typeof timeline.get === "function" ? timeline.get(normalizedKey) : null;
  if (Array.isArray(entries)) {
    let match = null;
    for (const entry of entries) {
      if (entry.effective_from && normalizedDateKey && entry.effective_from <= normalizedDateKey) {
        match = entry;
      } else if (entry.effective_from && normalizedDateKey && entry.effective_from > normalizedDateKey) {
        break;
      }
    }
    if (match) return { model_id: match.model_id, model: match.model };
  }
  const display = normalizeModel(rawModel) || DEFAULT_MODEL;
  return { model_id: normalizedKey, model: display };
}
function matchesCanonicalModelAtDate({ rawModel, canonicalModel, dateKey, timeline } = {}) {
  if (!canonicalModel) return true;
  const identity = resolveIdentityAtDate({ rawModel, dateKey, timeline });
  const filterIdentity = resolveIdentityAtDate({
    rawModel: canonicalModel,
    usageKey: canonicalModel,
    dateKey,
    timeline
  });
  return identity.model_id === filterIdentity.model_id;
}
function buildAliasTimeline({ usageModels, aliasRows } = {}) {
  const normalized = new Set(
    Array.isArray(usageModels) ? usageModels.map((model) => normalizeUsageModelKey(model)).filter(Boolean) : []
  );
  const timeline = /* @__PURE__ */ new Map();
  for (const row of Array.isArray(aliasRows) ? aliasRows : []) {
    const usageKey = normalizeUsageModelKey(row?.usage_model);
    const canonical = normalizeUsageModelKey(row?.canonical_model);
    if (!usageKey || !canonical) continue;
    if (normalized.size > 0 && !normalized.has(usageKey)) continue;
    const display = normalizeModel(row?.display_name) || canonical;
    const effective = extractDateKey(row?.effective_from || "");
    if (!effective) continue;
    const entry = { model_id: canonical, model: display, effective_from: effective };
    const list = timeline.get(usageKey);
    if (list) {
      list.push(entry);
    } else {
      timeline.set(usageKey, [entry]);
    }
  }
  for (const list of timeline.values()) {
    list.sort((a, b) => String(a.effective_from).localeCompare(String(b.effective_from)));
  }
  return timeline;
}
async function fetchAliasRows({ edgeClient, usageModels, effectiveDate } = {}) {
  const models = Array.isArray(usageModels) ? usageModels.map((model) => normalizeUsageModelKey(model)).filter(Boolean) : [];
  const database = edgeClient?.database;
  if (!models.length || !database || typeof database.from !== "function") return [];
  const dateKey = extractDateKey(effectiveDate) || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  const dateKeyNext = nextDateKey(dateKey) || dateKey;
  const query = database.from("vibeusage_model_aliases").select("usage_model,canonical_model,display_name,effective_from");
  if (!query || typeof query.eq !== "function" || typeof query.in !== "function" || typeof query.lt !== "function" || typeof query.order !== "function") {
    return [];
  }
  const result = await query.eq("active", true).in("usage_model", models).lt("effective_from", dateKeyNext).order("effective_from", { ascending: true });
  const { data, error } = readQueryOutcome(result, query);
  if (error || !Array.isArray(data)) return [];
  return data;
}
if (!globalThis[CORE_KEY3]) {
  Object.defineProperty(globalThis, CORE_KEY3, {
    value: {
      normalizeModel,
      normalizeUsageModel,
      applyUsageModelFilter,
      getModelParam,
      normalizeDateKey,
      extractDateKey,
      normalizeUsageModelKey,
      buildIdentityMap,
      applyModelIdentity,
      resolveModelIdentity,
      resolveUsageModelsForCanonical,
      resolveUsageFilterContext,
      resolveUsageTimelineContext,
      resolveIdentityAtDate,
      matchesCanonicalModelAtDate,
      buildAliasTimeline,
      fetchAliasRows
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/shared/env-core.mjs
var CORE_KEY4 = "__vibeusageEnvCore";
var DEFAULT_BASE_URL = "http://insforge:7130";
var DEFAULT_USAGE_MAX_DAYS = 800;
var DEFAULT_SLOW_QUERY_THRESHOLD_MS = 2e3;
var DEFAULT_PRICING_MODEL = "gpt-5.2-codex";
var DEFAULT_PRICING_SOURCE = "openrouter";
var runtimePrimitivesCore = globalThis.__vibeusageRuntimePrimitivesCore;
if (!runtimePrimitivesCore) throw new Error("runtime primitives core not initialized");
var usageModelCore = globalThis.__vibeusageUsageModelCore;
if (!usageModelCore) throw new Error("usage-model core not initialized");
function readDenoEnvValue(key) {
  try {
    if (typeof Deno !== "undefined" && Deno?.env?.get) {
      const value = Deno.env.get(key);
      return value == null ? null : value;
    }
  } catch (_error) {
  }
  return null;
}
function readEnvValue(key) {
  const denoValue = readDenoEnvValue(key);
  if (denoValue != null) return denoValue;
  try {
    if (typeof process !== "undefined" && process?.env) {
      const value = process.env[key];
      if (value != null) return value;
    }
  } catch (_error) {
  }
  return null;
}
function clampInt(value, min, max) {
  const n = Number(value);
  if (!Number.isFinite(n)) return min;
  return Math.min(max, Math.max(min, Math.floor(n)));
}
function getBaseUrl() {
  return readDenoEnvValue("INSFORGE_INTERNAL_URL") || DEFAULT_BASE_URL;
}
function firstHeaderValue(value) {
  if (typeof value !== "string") return null;
  const first = value.split(",")[0]?.trim();
  return first || null;
}
function getForwardedBaseUrl(request) {
  const headers = request?.headers;
  if (!headers || typeof headers.get !== "function") return null;
  const forwardedHost = firstHeaderValue(headers.get("x-forwarded-host"));
  const host = forwardedHost || firstHeaderValue(headers.get("host"));
  if (!host) return null;
  const proto = firstHeaderValue(headers.get("x-forwarded-proto")) || "https";
  return `${proto}://${host}`;
}
function getRequestBaseUrl(request) {
  const forwarded = getForwardedBaseUrl(request);
  if (forwarded) return forwarded;
  if (request && typeof request.url === "string") {
    try {
      const url = new URL(request.url);
      if (url.origin && url.origin !== "null") return url.origin;
    } catch (_error) {
    }
  }
  return getBaseUrl();
}
function getServiceRoleKey() {
  return readDenoEnvValue("INSFORGE_SERVICE_ROLE_KEY") || readDenoEnvValue("SERVICE_ROLE_KEY") || readDenoEnvValue("INSFORGE_API_KEY") || readDenoEnvValue("API_KEY") || null;
}
function getAnonKey() {
  return readDenoEnvValue("ANON_KEY") || readDenoEnvValue("INSFORGE_ANON_KEY") || null;
}
function getJwtSecret() {
  return readDenoEnvValue("INSFORGE_JWT_SECRET") || null;
}
function getUsageMaxDays() {
  const raw = readEnvValue("VIBEUSAGE_USAGE_MAX_DAYS");
  if (raw == null || raw === "") return DEFAULT_USAGE_MAX_DAYS;
  const n = Number(raw);
  if (!Number.isFinite(n) || n <= 0) return DEFAULT_USAGE_MAX_DAYS;
  return clampInt(n, 1, 5e3);
}
function getSlowQueryThresholdMs() {
  const raw = readEnvValue("VIBEUSAGE_SLOW_QUERY_MS");
  if (raw == null || raw === "") return DEFAULT_SLOW_QUERY_THRESHOLD_MS;
  const n = Number(raw);
  if (!Number.isFinite(n)) return DEFAULT_SLOW_QUERY_THRESHOLD_MS;
  if (n <= 0) return 0;
  return clampInt(n, 1, 6e4);
}
function normalizePricingModel(value) {
  const normalized = usageModelCore.normalizeModel?.(value) || null;
  if (!normalized || normalized.toLowerCase() === "unknown") return null;
  return normalized;
}
function getPricingDefaults() {
  const primaryModel = normalizePricingModel(readEnvValue("VIBEUSAGE_PRICING_MODEL"));
  const primarySource = runtimePrimitivesCore.normalizeSource(
    readEnvValue("VIBEUSAGE_PRICING_SOURCE")
  );
  return {
    model: primaryModel || DEFAULT_PRICING_MODEL,
    source: primarySource || DEFAULT_PRICING_SOURCE
  };
}
if (!globalThis[CORE_KEY4]) {
  Object.defineProperty(globalThis, CORE_KEY4, {
    value: {
      readEnvValue,
      clampInt,
      getBaseUrl,
      getRequestBaseUrl,
      getServiceRoleKey,
      getAnonKey,
      getJwtSecret,
      getUsageMaxDays,
      getSlowQueryThresholdMs,
      getPricingDefaults
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/functions-esm/shared/env.js
var envCore = globalThis.__vibeusageEnvCore;
if (!envCore) throw new Error("env core not initialized");
var getBaseUrl2 = envCore.getBaseUrl;
var getRequestBaseUrl2 = envCore.getRequestBaseUrl;
var getServiceRoleKey2 = envCore.getServiceRoleKey;
var getAnonKey2 = envCore.getAnonKey;
var getJwtSecret2 = envCore.getJwtSecret;
var getUsageMaxDays2 = envCore.getUsageMaxDays;
var getSlowQueryThresholdMs2 = envCore.getSlowQueryThresholdMs;
var getPricingDefaults2 = envCore.getPricingDefaults;

// insforge-src/functions-esm/shared/insforge-client.js
var cachedCreateClientPromise = null;
async function loadSdkCreateClient() {
  if (typeof Deno === "undefined") return null;
  try {
    const mod = await import("npm:@insforge/sdk");
    return typeof mod?.createClient === "function" ? mod.createClient : null;
  } catch (_error) {
    return null;
  }
}
async function getCreateClient() {
  const injected = globalThis.createClient;
  if (typeof injected === "function") return injected;
  if (!cachedCreateClientPromise) {
    cachedCreateClientPromise = loadSdkCreateClient();
  }
  const sdkCreateClient = await cachedCreateClientPromise;
  if (typeof sdkCreateClient === "function") return sdkCreateClient;
  throw new Error("Missing createClient");
}
async function createEdgeClient(options) {
  const createClient = await getCreateClient();
  return createClient(options);
}

// insforge-src/shared/public-sharing-core.mjs
var CORE_KEY5 = "__vibeusagePublicSharingCore";
var PUBLIC_USER_TOKEN_RE = /^pv1-([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/;
function buildPublicShareToken(userId) {
  if (typeof userId !== "string") return "";
  const normalized = userId.trim().toLowerCase();
  if (!normalized) return "";
  return `pv1-${normalized}`;
}
function disabledState() {
  return {
    enabled: false,
    updated_at: null,
    share_token: null
  };
}
function normalizeUpdatedAt(value) {
  return typeof value === "string" ? value : null;
}
function normalizeToken(value) {
  if (typeof value !== "string") return null;
  const token = value.trim();
  if (!token) return null;
  if (token.length > 256) return null;
  return token;
}
function normalizeShareToken(value) {
  const token = normalizeToken(value);
  if (!token) return null;
  const normalized = token.toLowerCase();
  if (token !== normalized) return null;
  const publicUserMatch = normalized.match(PUBLIC_USER_TOKEN_RE);
  if (publicUserMatch?.[1]) {
    return { kind: "user", userId: publicUserMatch[1] };
  }
  return null;
}
function isPublicShareToken(value) {
  return Boolean(normalizeShareToken(value));
}
async function resolvePublicUserId({ dbClient, token }) {
  if (!dbClient || !token) return null;
  const { data, error } = await dbClient.database.from("vibeusage_public_views").select("user_id").eq("user_id", token.userId).is("revoked_at", null).maybeSingle();
  if (error || !data?.user_id) return null;
  return data.user_id;
}
async function resolvePublicView({
  baseUrl,
  shareToken,
  serviceRoleKey,
  anonKey,
  createServiceClient
} = {}) {
  const token = normalizeShareToken(shareToken);
  if (!token) {
    return { ok: false, edgeClient: null, userId: null };
  }
  if (typeof serviceRoleKey !== "string" || serviceRoleKey.length === 0) {
    return { ok: false, edgeClient: null, userId: null };
  }
  if (typeof createServiceClient !== "function") {
    return { ok: false, edgeClient: null, userId: null };
  }
  const dbClient = await createServiceClient({
    baseUrl,
    anonKey: anonKey || serviceRoleKey,
    edgeFunctionToken: serviceRoleKey
  });
  const resolvedUserId = await resolvePublicUserId({ dbClient, token });
  if (!resolvedUserId) {
    return { ok: false, edgeClient: null, userId: null };
  }
  const { data: settings, error: settingsErr } = await dbClient.database.from("vibeusage_user_settings").select("leaderboard_public").eq("user_id", resolvedUserId).maybeSingle();
  if (settingsErr || settings?.leaderboard_public !== true) {
    return { ok: false, edgeClient: null, userId: null };
  }
  return { ok: true, edgeClient: dbClient, userId: resolvedUserId };
}
async function getPublicVisibilityState({ edgeClient, userId }) {
  if (!edgeClient || typeof userId !== "string" || userId.trim().length === 0) {
    return disabledState();
  }
  try {
    const { data, error } = await edgeClient.database.from("vibeusage_public_views").select("user_id,revoked_at,updated_at").eq("user_id", userId).maybeSingle();
    if (error) return disabledState();
    const enabled = Boolean(data && !data.revoked_at);
    return {
      enabled,
      updated_at: normalizeUpdatedAt(data?.updated_at),
      share_token: enabled ? buildPublicShareToken(userId) : null
    };
  } catch (_error) {
    return disabledState();
  }
}
async function setPublicVisibilityState({
  edgeClient,
  userId,
  enabled,
  nowIso,
  sha256Hex: sha256Hex3
} = {}) {
  if (!edgeClient) throw new TypeError("edgeClient is required");
  if (typeof userId !== "string" || userId.trim().length === 0) {
    throw new TypeError("userId is required");
  }
  if (typeof enabled !== "boolean") {
    throw new TypeError("enabled must be boolean");
  }
  if (typeof sha256Hex3 !== "function") {
    throw new TypeError("sha256Hex is required");
  }
  if (enabled) {
    await enablePublicVisibility({ edgeClient, userId, nowIso, sha256Hex: sha256Hex3 });
  } else {
    await disablePublicVisibility({ edgeClient, userId, nowIso });
  }
  return getPublicVisibilityState({ edgeClient, userId });
}
async function enablePublicVisibility({ edgeClient, userId, nowIso, sha256Hex: sha256Hex3 }) {
  const table = edgeClient.database.from("vibeusage_public_views");
  const shareToken = buildPublicShareToken(userId);
  const tokenHash = await sha256Hex3(shareToken);
  const updatedAt = typeof nowIso === "string" && nowIso ? nowIso : (/* @__PURE__ */ new Date()).toISOString();
  const nextRow = {
    user_id: userId,
    token_hash: tokenHash,
    revoked_at: null,
    updated_at: updatedAt
  };
  if (typeof table.upsert === "function") {
    try {
      const { error: upsertErr } = await table.upsert([nextRow], { onConflict: "user_id" });
      if (!upsertErr) return;
    } catch (_error) {
    }
  }
  const { data: existing, error: selectErr } = await table.select("user_id").eq("user_id", userId).maybeSingle();
  if (selectErr) throw new Error(selectErr.message || "Failed to select public visibility row");
  if (existing?.user_id) {
    const { error: updateErr } = await table.update({ token_hash: tokenHash, revoked_at: null, updated_at: updatedAt }).eq("user_id", userId);
    if (updateErr) throw new Error(updateErr.message || "Failed to update public visibility row");
    return;
  }
  const { error: insertErr } = await table.insert([nextRow]);
  if (insertErr) throw new Error(insertErr.message || "Failed to insert public visibility row");
}
async function disablePublicVisibility({ edgeClient, userId, nowIso }) {
  const updatedAt = typeof nowIso === "string" && nowIso ? nowIso : (/* @__PURE__ */ new Date()).toISOString();
  const { error } = await edgeClient.database.from("vibeusage_public_views").update({ revoked_at: updatedAt, updated_at: updatedAt }).eq("user_id", userId);
  if (error) throw new Error(error.message || "Failed to revoke public visibility row");
}
if (!globalThis[CORE_KEY5]) {
  Object.defineProperty(globalThis, CORE_KEY5, {
    value: {
      buildPublicShareToken,
      isPublicShareToken,
      resolvePublicView,
      getPublicVisibilityState,
      setPublicVisibilityState
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/functions-esm/shared/public-view.js
var publicSharingCore = globalThis.__vibeusagePublicSharingCore;
if (!publicSharingCore) throw new Error("public sharing core not initialized");
var isPublicShareToken2 = publicSharingCore.isPublicShareToken;

// insforge-src/functions-esm/shared/auth.js
var authCore = globalThis.__vibeusageAuthCore;
if (!authCore) throw new Error("auth core not initialized");
var getBearerToken2 = authCore.getBearerToken;
var isProjectAdminBearer2 = authCore.isProjectAdminBearer;

// insforge-src/shared/concurrency.mjs
var CORE_KEY6 = "__vibeusageConcurrencyCore";
var LIMITERS = /* @__PURE__ */ new Map();
function createConcurrencyGuard({
  name,
  envKey,
  defaultMax = 0,
  retryAfterEnvKey,
  defaultRetryAfterMs = 1e3
}) {
  const maxInflight = readEnvInt(envKey, defaultMax);
  if (!Number.isFinite(maxInflight) || maxInflight <= 0) return null;
  const retryAfterMs = readEnvInt(retryAfterEnvKey, defaultRetryAfterMs);
  return getLimiter({ name, maxInflight, retryAfterMs });
}
function getLimiter({ name, maxInflight, retryAfterMs }) {
  const key = name || "default";
  const existing = LIMITERS.get(key);
  if (existing && existing.maxInflight === maxInflight && existing.retryAfterMs === retryAfterMs) {
    return existing;
  }
  const limiter = createLimiter({ maxInflight, retryAfterMs });
  LIMITERS.set(key, limiter);
  return limiter;
}
function createLimiter({ maxInflight, retryAfterMs }) {
  let inflight = 0;
  function acquire() {
    if (inflight >= maxInflight) {
      const retryAfterSeconds = Math.max(1, Math.ceil(Math.max(0, retryAfterMs) / 1e3));
      return {
        ok: false,
        retryAfterMs,
        headers: {
          "Retry-After": String(retryAfterSeconds)
        }
      };
    }
    inflight += 1;
    return {
      ok: true,
      release() {
        inflight = Math.max(0, inflight - 1);
      }
    };
  }
  return {
    maxInflight,
    retryAfterMs,
    acquire
  };
}
function readEnvInt(key, fallback) {
  if (!key) return fallback;
  const keys = Array.isArray(key) ? key : [key];
  for (const candidate of keys) {
    if (!candidate) continue;
    const raw = readEnvValue2(candidate);
    if (raw == null || raw === "") continue;
    const n = Number(raw);
    if (!Number.isFinite(n)) continue;
    return Math.floor(n);
  }
  return fallback;
}
function readEnvValue2(key) {
  try {
    if (typeof Deno !== "undefined" && Deno?.env?.get) {
      const value = Deno.env.get(key);
      if (value !== void 0) return value;
    }
  } catch (_error) {
  }
  try {
    if (typeof process !== "undefined" && process?.env) {
      return process.env[key];
    }
  } catch (_error) {
  }
  return null;
}
if (!globalThis[CORE_KEY6]) {
  Object.defineProperty(globalThis, CORE_KEY6, {
    value: {
      createConcurrencyGuard
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/shared/crypto-core.mjs
var CORE_KEY7 = "__vibeusageCryptoCore";
async function sha256Hex(input) {
  const data = new TextEncoder().encode(String(input ?? ""));
  const hash = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(hash)).map((byte) => byte.toString(16).padStart(2, "0")).join("");
}
if (!globalThis[CORE_KEY7]) {
  Object.defineProperty(globalThis, CORE_KEY7, {
    value: {
      sha256Hex
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/functions-esm/shared/crypto.js
var cryptoCore = globalThis.__vibeusageCryptoCore;
if (!cryptoCore) throw new Error("crypto core not initialized");
var sha256Hex2 = cryptoCore.sha256Hex;

// insforge-src/shared/http-core.mjs
var CORE_KEY8 = "__vibeusageHttpCore";
var corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey"
};
function handleOptions(request) {
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }
  return null;
}
function json(body, status = 200, extraHeaders = null) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/json",
      ...extraHeaders || {}
    }
  });
}
function requireMethod(request, method) {
  if (request.method !== method) return json({ error: "Method not allowed" }, 405);
  return null;
}
async function readJson(request) {
  if (!request.headers.get("Content-Type")?.includes("application/json")) {
    return { error: "Content-Type must be application/json", status: 415, data: null };
  }
  try {
    const data = await request.json();
    return { error: null, status: 200, data };
  } catch (_error) {
    return { error: "Invalid JSON", status: 400, data: null };
  }
}
if (!globalThis[CORE_KEY8]) {
  Object.defineProperty(globalThis, CORE_KEY8, {
    value: {
      corsHeaders,
      handleOptions,
      json,
      requireMethod,
      readJson
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/functions-esm/shared/http.js
var httpCore = globalThis.__vibeusageHttpCore;
if (!httpCore) throw new Error("http core not initialized");
var corsHeaders2 = httpCore.corsHeaders;
var handleOptions2 = httpCore.handleOptions;
var json2 = httpCore.json;
var requireMethod2 = httpCore.requireMethod;
var readJson2 = httpCore.readJson;

// insforge-src/shared/logging-core.mjs
var CORE_KEY9 = "__vibeusageLoggingCore";
var envCore2 = globalThis.__vibeusageEnvCore;
if (!envCore2) throw new Error("env core not initialized");
function createRequestId() {
  if (globalThis?.crypto?.randomUUID) return globalThis.crypto.randomUUID();
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
function errorCodeFromStatus(status) {
  if (typeof status !== "number") return "UNKNOWN_ERROR";
  if (status >= 500) return "SERVER_ERROR";
  if (status >= 400) return "CLIENT_ERROR";
  return null;
}
function getResponseStatus(response) {
  if (response && typeof response.status === "number") return response.status;
  return null;
}
function resolveFunctionName(functionName, request) {
  if (request && typeof request.url === "string") {
    try {
      const url = new URL(request.url);
      const match = url.pathname.match(/\/functions\/([^/?#]+)/);
      if (match && match[1]) return match[1];
    } catch (_error) {
    }
  }
  return functionName;
}
function createLogger({ functionName }) {
  const requestId = createRequestId();
  const startMs = Date.now();
  let upstreamStatus = null;
  let upstreamLatencyMs = null;
  function recordUpstream(status, latencyMs) {
    upstreamStatus = typeof status === "number" ? status : null;
    upstreamLatencyMs = typeof latencyMs === "number" ? latencyMs : null;
  }
  async function fetchWithUpstream(url, init) {
    const upstreamStart = Date.now();
    try {
      const res = await fetch(url, init);
      recordUpstream(res.status, Date.now() - upstreamStart);
      return res;
    } catch (error) {
      recordUpstream(null, Date.now() - upstreamStart);
      throw error;
    }
  }
  function log({ stage, status, errorCode, ...extra }) {
    const payload = {
      ...extra || {},
      request_id: requestId,
      function: functionName,
      stage: stage || "response",
      status: typeof status === "number" ? status : null,
      latency_ms: Date.now() - startMs,
      error_code: errorCode ?? errorCodeFromStatus(status),
      upstream_status: upstreamStatus ?? null,
      upstream_latency_ms: upstreamLatencyMs ?? null
    };
    console.log(JSON.stringify(payload));
  }
  return {
    requestId,
    log,
    fetch: fetchWithUpstream
  };
}
function withRequestLogging(functionName, handler) {
  return async function(request) {
    const resolvedName = resolveFunctionName(functionName, request);
    const logger = createLogger({ functionName: resolvedName });
    try {
      const response = await handler(request, logger);
      logger.log({ stage: "response", status: getResponseStatus(response) });
      return response;
    } catch (error) {
      logger.log({ stage: "exception", status: 500, errorCode: "UNHANDLED_EXCEPTION" });
      throw error;
    }
  };
}
function logSlowQuery(logger, fields) {
  if (!logger || typeof logger.log !== "function") return;
  const durationMs = Number(fields?.duration_ms ?? fields?.durationMs);
  if (!Number.isFinite(durationMs)) return;
  const thresholdMs = envCore2.getSlowQueryThresholdMs();
  if (durationMs < thresholdMs) return;
  logger.log({
    stage: "slow_query",
    status: 200,
    ...fields || {},
    duration_ms: Math.round(durationMs)
  });
}
function getSlowQueryThresholdMs3() {
  return envCore2.getSlowQueryThresholdMs();
}
if (!globalThis[CORE_KEY9]) {
  Object.defineProperty(globalThis, CORE_KEY9, {
    value: {
      createLogger,
      withRequestLogging,
      logSlowQuery,
      getSlowQueryThresholdMs: getSlowQueryThresholdMs3
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/functions-esm/shared/logging.js
var loggingCore = globalThis.__vibeusageLoggingCore;
if (!loggingCore) throw new Error("logging core not initialized");
var createLogger2 = loggingCore.createLogger;
var withRequestLogging2 = loggingCore.withRequestLogging;
var logSlowQuery2 = loggingCore.logSlowQuery;

// insforge-src/shared/date-core.mjs
var CORE_KEY10 = "__vibeusageDateCore";
var envCore3 = globalThis.__vibeusageEnvCore;
if (!envCore3) throw new Error("env core not initialized");
var TIMEZONE_FORMATTERS = /* @__PURE__ */ new Map();
function isDate(value) {
  return typeof value === "string" && /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(value);
}
function toUtcDay(date) {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
}
function formatDateUTC(date) {
  return toUtcDay(date).toISOString().slice(0, 10);
}
function normalizeIso(value) {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  const dt = new Date(trimmed);
  if (!Number.isFinite(dt.getTime())) return null;
  return dt.toISOString();
}
function normalizeDateRange(fromRaw, toRaw) {
  const today = /* @__PURE__ */ new Date();
  const toDefault = formatDateUTC(today);
  const fromDefault = formatDateUTC(
    new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate() - 29))
  );
  const from = isDate(fromRaw) ? fromRaw : fromDefault;
  const to = isDate(toRaw) ? toRaw : toDefault;
  return { from, to };
}
function parseUtcDateString(value) {
  if (!isDate(value)) return null;
  const [year, month, day] = value.split("-").map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  if (!Number.isFinite(date.getTime())) return null;
  return formatDateUTC(date) === value ? date : null;
}
function addUtcDays(date, days) {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() + days));
}
function computeHeatmapWindowUtc({ weeks, weekStartsOn, to }) {
  const end = parseUtcDateString(to) || /* @__PURE__ */ new Date();
  const desired = weekStartsOn === "mon" ? 1 : 0;
  const endDow = end.getUTCDay();
  const endWeekStart = addUtcDays(end, -((endDow - desired + 7) % 7));
  const gridStart = addUtcDays(endWeekStart, -7 * (weeks - 1));
  return { from: formatDateUTC(gridStart), gridStart, end };
}
function getTimeZoneFormatter(timeZone) {
  if (TIMEZONE_FORMATTERS.has(timeZone)) return TIMEZONE_FORMATTERS.get(timeZone);
  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone,
    hour12: false,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit"
  });
  TIMEZONE_FORMATTERS.set(timeZone, formatter);
  return formatter;
}
function parseDateParts(value) {
  if (!isDate(value)) return null;
  const [year, month, day] = value.split("-").map(Number);
  if (!Number.isFinite(year) || !Number.isFinite(month) || !Number.isFinite(day)) return null;
  return { year, month, day };
}
function formatDateParts(parts) {
  if (!parts) return null;
  const year = Number(parts.year);
  const month = Number(parts.month);
  const day = Number(parts.day);
  if (!Number.isFinite(year) || !Number.isFinite(month) || !Number.isFinite(day)) return null;
  return `${String(year).padStart(4, "0")}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
}
function dateFromPartsUTC(parts) {
  if (!parts) return null;
  const year = Number(parts.year);
  const month = Number(parts.month) - 1;
  const day = Number(parts.day);
  const hour = Number(parts.hour || 0);
  const minute = Number(parts.minute || 0);
  const second = Number(parts.second || 0);
  if (!Number.isFinite(year) || !Number.isFinite(month) || !Number.isFinite(day)) return null;
  return new Date(Date.UTC(year, month, day, hour, minute, second));
}
function datePartsFromDateUTC(date) {
  return {
    year: date.getUTCFullYear(),
    month: date.getUTCMonth() + 1,
    day: date.getUTCDate(),
    hour: date.getUTCHours(),
    minute: date.getUTCMinutes(),
    second: date.getUTCSeconds()
  };
}
function addDatePartsDays(parts, days) {
  const base = dateFromPartsUTC(parts);
  if (!base) return null;
  return datePartsFromDateUTC(addUtcDays(base, days));
}
function addDatePartsMonths(parts, months) {
  if (!parts) return null;
  const year = Number(parts.year);
  const month = Number(parts.month) - 1 + Number(months || 0);
  const day = Number(parts.day || 1);
  if (!Number.isFinite(year) || !Number.isFinite(month) || !Number.isFinite(day)) return null;
  const dt = new Date(Date.UTC(year, month, day));
  return {
    year: dt.getUTCFullYear(),
    month: dt.getUTCMonth() + 1,
    day: dt.getUTCDate()
  };
}
function parseOffsetMinutes(raw) {
  if (raw == null || raw === "") return null;
  const value = String(raw).trim();
  if (!/^-?\d+$/.test(value)) return null;
  const offset = Number(value);
  if (!Number.isFinite(offset) || offset < -840 || offset > 840) return null;
  return Math.trunc(offset);
}
function normalizeTimeZone(tzRaw, offsetRaw) {
  const timeZoneValue = typeof tzRaw === "string" ? tzRaw.trim() : "";
  let timeZone = null;
  if (timeZoneValue) {
    try {
      getTimeZoneFormatter(timeZoneValue).format(/* @__PURE__ */ new Date(0));
      timeZone = timeZoneValue;
    } catch (_error) {
      timeZone = null;
    }
  }
  const offsetMinutes = parseOffsetMinutes(offsetRaw);
  if (timeZone) return { timeZone, offsetMinutes: null, source: "iana" };
  if (offsetMinutes != null) return { timeZone: null, offsetMinutes, source: "offset" };
  return { timeZone: null, offsetMinutes: 0, source: "utc" };
}
function getUsageTimeZoneContext(url) {
  if (!url?.searchParams) return normalizeTimeZone();
  return normalizeTimeZone(url.searchParams.get("tz"), url.searchParams.get("tz_offset_minutes"));
}
function isUtcTimeZone(tzContext) {
  if (!tzContext) return true;
  const tz = tzContext.timeZone;
  if (tz) {
    const upper = tz.toUpperCase();
    return upper === "UTC" || upper === "ETC/UTC" || upper === "ETC/GMT";
  }
  return Number(tzContext.offsetMinutes || 0) === 0;
}
function getTimeZoneParts(date, timeZone) {
  const parts = getTimeZoneFormatter(timeZone).formatToParts(date);
  let year = 0;
  let month = 0;
  let day = 0;
  let hour = 0;
  let minute = 0;
  let second = 0;
  for (const part of parts) {
    if (part.type === "year") year = Number(part.value);
    if (part.type === "month") month = Number(part.value);
    if (part.type === "day") day = Number(part.value);
    if (part.type === "hour") hour = Number(part.value);
    if (part.type === "minute") minute = Number(part.value);
    if (part.type === "second") second = Number(part.value);
  }
  return { year, month, day, hour, minute, second };
}
function getTimeZoneOffsetMinutes(date, timeZone) {
  const parts = getTimeZoneParts(date, timeZone);
  const asUtc = Date.UTC(
    parts.year,
    parts.month - 1,
    parts.day,
    parts.hour,
    parts.minute,
    parts.second
  );
  return Math.round((asUtc - date.getTime()) / 6e4);
}
function getLocalParts(date, tzContext) {
  if (tzContext?.timeZone) {
    return getTimeZoneParts(date, tzContext.timeZone);
  }
  const offsetMinutes = Number.isFinite(tzContext?.offsetMinutes) ? tzContext.offsetMinutes : 0;
  const shifted = new Date(date.getTime() + offsetMinutes * 6e4);
  return {
    year: shifted.getUTCFullYear(),
    month: shifted.getUTCMonth() + 1,
    day: shifted.getUTCDate(),
    hour: shifted.getUTCHours(),
    minute: shifted.getUTCMinutes(),
    second: shifted.getUTCSeconds()
  };
}
function formatLocalDateKey(date, tzContext) {
  return formatDateParts(getLocalParts(date, tzContext));
}
function localDatePartsToUtc(parts, tzContext) {
  const baseUtc = Date.UTC(
    Number(parts.year),
    Number(parts.month) - 1,
    Number(parts.day),
    Number(parts.hour || 0),
    Number(parts.minute || 0),
    Number(parts.second || 0)
  );
  if (tzContext?.timeZone) {
    let offset = getTimeZoneOffsetMinutes(new Date(baseUtc), tzContext.timeZone);
    let utc = baseUtc - offset * 6e4;
    const offset2 = getTimeZoneOffsetMinutes(new Date(utc), tzContext.timeZone);
    if (offset2 !== offset) {
      utc = baseUtc - offset2 * 6e4;
    }
    return new Date(utc);
  }
  const offsetMinutes = Number.isFinite(tzContext?.offsetMinutes) ? tzContext.offsetMinutes : 0;
  return new Date(baseUtc - offsetMinutes * 6e4);
}
function normalizeDateRangeLocal(fromRaw, toRaw, tzContext) {
  const todayParts = getLocalParts(/* @__PURE__ */ new Date(), tzContext);
  const toDefault = formatDateParts(todayParts);
  const fromDefault = formatDateParts(
    addDatePartsDays(
      { year: todayParts.year, month: todayParts.month, day: todayParts.day },
      -29
    )
  );
  return {
    from: isDate(fromRaw) ? fromRaw : fromDefault,
    to: isDate(toRaw) ? toRaw : toDefault
  };
}
function listDateStrings(from, to) {
  const startParts = parseDateParts(from);
  const endParts = parseDateParts(to);
  if (!startParts || !endParts) return [];
  const start = dateFromPartsUTC(startParts);
  const end = dateFromPartsUTC(endParts);
  if (!start || !end || end < start) return [];
  const days = [];
  for (let cursor = start; cursor <= end; cursor = addUtcDays(cursor, 1)) {
    days.push(formatDateUTC(cursor));
  }
  return days;
}
function resolveUsageDateRangeLocal({ fromRaw, toRaw, tzContext, maxDays } = {}) {
  const resolvedMaxDays = Number.isFinite(maxDays) ? maxDays : getUsageMaxDays3();
  const { from, to } = normalizeDateRangeLocal(fromRaw, toRaw, tzContext);
  const dayKeys = listDateStrings(from, to);
  if (dayKeys.length > resolvedMaxDays) {
    return {
      ok: false,
      error: `Date range too large (max ${resolvedMaxDays} days)`
    };
  }
  const startParts = parseDateParts(from);
  const endParts = parseDateParts(to);
  if (!startParts || !endParts) {
    return {
      ok: false,
      error: "Invalid date range"
    };
  }
  const startUtc = localDatePartsToUtc(startParts, tzContext);
  const endUtc = localDatePartsToUtc(addDatePartsDays(endParts, 1), tzContext);
  if (!Number.isFinite(startUtc.getTime()) || !Number.isFinite(endUtc.getTime())) {
    return {
      ok: false,
      error: "Invalid date range"
    };
  }
  return {
    ok: true,
    from,
    to,
    dayKeys,
    startParts,
    endParts,
    startUtc,
    endUtc,
    startIso: startUtc.toISOString(),
    endIso: endUtc.toISOString(),
    maxDays: resolvedMaxDays
  };
}
function getUsageMaxDays3() {
  return envCore3.getUsageMaxDays();
}
function isWithinInterval(lastSyncAt, minutes, nowIso) {
  const lastIso = normalizeIso(lastSyncAt);
  if (!lastIso) return false;
  const lastMs = Date.parse(lastIso);
  if (!Number.isFinite(lastMs)) return false;
  const windowMs = Math.max(0, minutes) * 60 * 1e3;
  if (windowMs <= 0) return false;
  const nowValue = nowIso == null ? Date.now() : Date.parse(normalizeIso(nowIso) || "");
  if (!Number.isFinite(nowValue)) return false;
  return nowValue - lastMs < windowMs;
}
if (!globalThis[CORE_KEY10]) {
  Object.defineProperty(globalThis, CORE_KEY10, {
    value: {
      isDate,
      toUtcDay,
      formatDateUTC,
      normalizeIso,
      normalizeDateRange,
      parseUtcDateString,
      addUtcDays,
      computeHeatmapWindowUtc,
      parseDateParts,
      formatDateParts,
      dateFromPartsUTC,
      datePartsFromDateUTC,
      addDatePartsDays,
      addDatePartsMonths,
      normalizeTimeZone,
      getUsageTimeZoneContext,
      isUtcTimeZone,
      getTimeZoneOffsetMinutes,
      getLocalParts,
      formatLocalDateKey,
      localDatePartsToUtc,
      normalizeDateRangeLocal,
      listDateStrings,
      resolveUsageDateRangeLocal,
      getUsageMaxDays: getUsageMaxDays3,
      isWithinInterval
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/shared/usage-metrics-core.mjs
var CORE_KEY11 = "__vibeusageUsageMetricsCore";
var BILLABLE_INPUT_OUTPUT_REASONING = /* @__PURE__ */ new Set(["codex", "every-code"]);
var BILLABLE_ADD_ALL = /* @__PURE__ */ new Set(["claude", "opencode"]);
var BILLABLE_TOTAL = /* @__PURE__ */ new Set(["gemini"]);
var runtimePrimitivesCore2 = globalThis.__vibeusageRuntimePrimitivesCore;
if (!runtimePrimitivesCore2) throw new Error("runtime primitives core not initialized");
function createTotals() {
  return {
    total_tokens: 0n,
    billable_total_tokens: 0n,
    input_tokens: 0n,
    cached_input_tokens: 0n,
    output_tokens: 0n,
    reasoning_output_tokens: 0n
  };
}
function addRowTotals(target, row) {
  if (!target || !row) return;
  target.total_tokens += runtimePrimitivesCore2.toBigInt(row?.total_tokens);
  target.billable_total_tokens += runtimePrimitivesCore2.toBigInt(row?.billable_total_tokens);
  target.input_tokens += runtimePrimitivesCore2.toBigInt(row?.input_tokens);
  target.cached_input_tokens += runtimePrimitivesCore2.toBigInt(row?.cached_input_tokens);
  target.output_tokens += runtimePrimitivesCore2.toBigInt(row?.output_tokens);
  target.reasoning_output_tokens += runtimePrimitivesCore2.toBigInt(row?.reasoning_output_tokens);
}
function computeBillableTotalTokens({ source, totals } = {}) {
  const normalizedSource = runtimePrimitivesCore2.normalizeSource(source) || "unknown";
  const input = runtimePrimitivesCore2.toBigInt(totals?.input_tokens);
  const cached = runtimePrimitivesCore2.toBigInt(totals?.cached_input_tokens);
  const output = runtimePrimitivesCore2.toBigInt(totals?.output_tokens);
  const reasoning = runtimePrimitivesCore2.toBigInt(totals?.reasoning_output_tokens);
  const total = runtimePrimitivesCore2.toBigInt(totals?.total_tokens);
  const hasTotal = Boolean(totals && Object.prototype.hasOwnProperty.call(totals, "total_tokens"));
  if (BILLABLE_TOTAL.has(normalizedSource)) return total;
  if (BILLABLE_ADD_ALL.has(normalizedSource)) return input + cached + output + reasoning;
  if (BILLABLE_INPUT_OUTPUT_REASONING.has(normalizedSource)) return input + output + reasoning;
  if (hasTotal) return total;
  return input + output + reasoning;
}
function resolveBillableTotals({
  row,
  source,
  totals,
  billableField = "billable_total_tokens",
  hasStoredBillable
} = {}) {
  const stored = typeof hasStoredBillable === "boolean" ? hasStoredBillable : Boolean(
    row && Object.prototype.hasOwnProperty.call(row, billableField) && row[billableField] != null
  );
  const resolvedTotals = totals || row;
  const billable = stored ? runtimePrimitivesCore2.toBigInt(row?.[billableField]) : computeBillableTotalTokens({ source, totals: resolvedTotals });
  return { billable, hasStoredBillable: stored };
}
function applyTotalsAndBillable({ totals, row, billable, hasStoredBillable } = {}) {
  if (!totals || !row) return;
  addRowTotals(totals, row);
  if (!hasStoredBillable) {
    totals.billable_total_tokens += runtimePrimitivesCore2.toBigInt(billable);
  }
}
function getSourceEntry(map, source) {
  if (map.has(source)) return map.get(source);
  const entry = { source, totals: createTotals() };
  map.set(source, entry);
  return entry;
}
function resolveDisplayName(identityMap, modelId) {
  if (!modelId || !identityMap || typeof identityMap.values !== "function") return modelId || null;
  for (const entry of identityMap.values()) {
    if (entry?.model_id === modelId && entry?.model) return entry.model;
  }
  return modelId;
}
function deriveDisplayModel(value) {
  if (value == null) return null;
  const text = String(value).trim();
  if (!text) return null;
  const parts = text.split("/").filter(Boolean);
  return parts.length > 1 ? parts[parts.length - 1] : text;
}
function buildPricingBucketKey(sourceKey, usageKey, dateKey) {
  return JSON.stringify([sourceKey || "", usageKey || "", dateKey || ""]);
}
function parsePricingBucketKey(bucketKey, defaultDate) {
  if (typeof bucketKey === "string" && bucketKey.startsWith("[")) {
    try {
      const parsed = JSON.parse(bucketKey);
      if (Array.isArray(parsed)) {
        const usageKey = parsed[1] ?? parsed[0] ?? "";
        const dateKey = parsed[2] ?? defaultDate;
        return { usageKey: String(usageKey || ""), dateKey: String(dateKey || defaultDate) };
      }
    } catch (_error) {
    }
  }
  if (typeof bucketKey === "string") {
    const parts = bucketKey.split("::");
    if (parts.length >= 3) return { usageKey: parts[1], dateKey: parts[2] || defaultDate };
    if (parts.length === 2) return { usageKey: parts[0], dateKey: parts[1] || defaultDate };
    return { usageKey: bucketKey, dateKey: defaultDate };
  }
  return { usageKey: bucketKey, dateKey: defaultDate };
}
function buildUsageTotalsPayload(totals, extra) {
  const payload = {
    total_tokens: runtimePrimitivesCore2.toBigInt(totals?.total_tokens).toString(),
    billable_total_tokens: runtimePrimitivesCore2.toBigInt(totals?.billable_total_tokens).toString(),
    input_tokens: runtimePrimitivesCore2.toBigInt(totals?.input_tokens).toString(),
    cached_input_tokens: runtimePrimitivesCore2.toBigInt(totals?.cached_input_tokens).toString(),
    output_tokens: runtimePrimitivesCore2.toBigInt(totals?.output_tokens).toString(),
    reasoning_output_tokens: runtimePrimitivesCore2.toBigInt(totals?.reasoning_output_tokens).toString()
  };
  return extra && typeof extra === "object" ? { ...payload, ...extra } : payload;
}
function buildUsageBucketPayload(bucket, extra) {
  return buildUsageTotalsPayload(
    {
      total_tokens: bucket?.total,
      billable_total_tokens: bucket?.billable,
      input_tokens: bucket?.input,
      cached_input_tokens: bucket?.cached,
      output_tokens: bucket?.output,
      reasoning_output_tokens: bucket?.reasoning
    },
    extra
  );
}
var coreValue = {
  createTotals,
  addRowTotals,
  computeBillableTotalTokens,
  resolveBillableTotals,
  applyTotalsAndBillable,
  getSourceEntry,
  resolveDisplayName,
  deriveDisplayModel,
  buildPricingBucketKey,
  parsePricingBucketKey,
  buildUsageTotalsPayload,
  buildUsageBucketPayload
};
if (globalThis[CORE_KEY11] && typeof globalThis[CORE_KEY11] === "object") {
  Object.assign(globalThis[CORE_KEY11], coreValue);
} else {
  Object.defineProperty(globalThis, CORE_KEY11, {
    value: coreValue,
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/shared/core/ingest.mjs
var CORE_KEY12 = "__vibeusageIngestCore";
var DEFAULT_MODEL2 = "unknown";
var BILLABLE_RULE_VERSION = 1;
var dateCore = globalThis.__vibeusageDateCore;
if (!dateCore) throw new Error("date core not initialized");
var runtimePrimitivesCore3 = globalThis.__vibeusageRuntimePrimitivesCore;
if (!runtimePrimitivesCore3) throw new Error("runtime primitives core not initialized");
var usageModelCore2 = globalThis.__vibeusageUsageModelCore;
if (!usageModelCore2) throw new Error("usage-model core not initialized");
var usageMetricsCore = globalThis.__vibeusageUsageMetricsCore;
if (!usageMetricsCore) throw new Error("usage metrics core not initialized");
var { normalizeIso: normalizeIso2 } = dateCore;
var { normalizeSource: normalizeSource2 } = runtimePrimitivesCore3;
var { normalizeUsageModel: normalizeUsageModel2 } = usageModelCore2;
var { computeBillableTotalTokens: computeBillableTotalTokens2 } = usageMetricsCore;
function normalizeHourlyPayload(data) {
  if (Array.isArray(data)) return data;
  if (data && typeof data === "object") {
    if (Array.isArray(data.hourly)) return data.hourly;
    if (Array.isArray(data.data)) return data.data;
    if (data.data && typeof data.data === "object" && Array.isArray(data.data.hourly)) {
      return data.data.hourly;
    }
  }
  return null;
}
function normalizeProjectHourlyPayload(data) {
  if (!data || typeof data !== "object") return null;
  if (Array.isArray(data.project_hourly)) return data.project_hourly;
  if (data.data && typeof data.data === "object" && Array.isArray(data.data.project_hourly)) {
    return data.data.project_hourly;
  }
  return null;
}
function normalizeDeviceSubscriptionsPayload(data) {
  if (!data || typeof data !== "object") return null;
  if (Array.isArray(data.device_subscriptions)) return data.device_subscriptions;
  if (data.data && typeof data.data === "object" && Array.isArray(data.data.device_subscriptions)) {
    return data.data.device_subscriptions;
  }
  return null;
}
function normalizeTextField(value, { lowerCase = false, maxLen = 128 } = {}) {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  const sliced = trimmed.length > maxLen ? trimmed.slice(0, maxLen) : trimmed;
  return lowerCase ? sliced.toLowerCase() : sliced;
}
function normalizeIsoField(value) {
  return normalizeIso2(value);
}
function parseUtcHalfHourStart(value) {
  if (typeof value !== "string" || value.trim() === "") return null;
  const dt = new Date(value);
  if (!Number.isFinite(dt.getTime())) return null;
  const minutes = dt.getUTCMinutes();
  if (minutes !== 0 && minutes !== 30 || dt.getUTCSeconds() !== 0 || dt.getUTCMilliseconds() !== 0) {
    return null;
  }
  const hourStart = new Date(
    Date.UTC(
      dt.getUTCFullYear(),
      dt.getUTCMonth(),
      dt.getUTCDate(),
      dt.getUTCHours(),
      minutes >= 30 ? 30 : 0,
      0,
      0
    )
  );
  return hourStart.toISOString();
}
function toNonNegativeInt(n) {
  if (typeof n !== "number") return null;
  if (!Number.isFinite(n)) return null;
  if (!Number.isInteger(n)) return null;
  if (n < 0) return null;
  return n;
}
function parseHourlyBucket(raw) {
  if (!raw || typeof raw !== "object") return { ok: false, error: "Invalid half-hour bucket" };
  const hourStart = parseUtcHalfHourStart(raw.hour_start);
  if (!hourStart) {
    return { ok: false, error: "hour_start must be an ISO timestamp at UTC half-hour boundary" };
  }
  const source = normalizeSource2(raw.source);
  const model = normalizeUsageModel2(raw.model) || DEFAULT_MODEL2;
  const input = toNonNegativeInt(raw.input_tokens);
  const cached = toNonNegativeInt(raw.cached_input_tokens);
  const output = toNonNegativeInt(raw.output_tokens);
  const reasoning = toNonNegativeInt(raw.reasoning_output_tokens);
  const total = toNonNegativeInt(raw.total_tokens);
  if ([input, cached, output, reasoning, total].some((n) => n == null)) {
    return { ok: false, error: "Token fields must be non-negative integers" };
  }
  return {
    ok: true,
    value: {
      source,
      model,
      hour_start: hourStart,
      input_tokens: input,
      cached_input_tokens: cached,
      output_tokens: output,
      reasoning_output_tokens: reasoning,
      total_tokens: total
    }
  };
}
function parseProjectHourlyBucket(raw) {
  if (!raw || typeof raw !== "object") {
    return { ok: false, error: "Invalid project half-hour bucket" };
  }
  const hourStart = parseUtcHalfHourStart(raw.hour_start);
  if (!hourStart) {
    return { ok: false, error: "hour_start must be an ISO timestamp at UTC half-hour boundary" };
  }
  const source = normalizeSource2(raw.source);
  const projectKey = typeof raw.project_key === "string" ? raw.project_key.trim() : "";
  const projectRef = typeof raw.project_ref === "string" ? raw.project_ref.trim() : "";
  const input = toNonNegativeInt(raw.input_tokens);
  const cached = toNonNegativeInt(raw.cached_input_tokens);
  const output = toNonNegativeInt(raw.output_tokens);
  const reasoning = toNonNegativeInt(raw.reasoning_output_tokens);
  const total = toNonNegativeInt(raw.total_tokens);
  if (!projectKey) return { ok: false, error: "project_key is required" };
  if (!projectRef) return { ok: false, error: "project_ref is required" };
  if ([input, cached, output, reasoning, total].some((n) => n == null)) {
    return { ok: false, error: "Token fields must be non-negative integers" };
  }
  return {
    ok: true,
    value: {
      source,
      project_key: projectKey,
      project_ref: projectRef,
      hour_start: hourStart,
      input_tokens: input,
      cached_input_tokens: cached,
      output_tokens: output,
      reasoning_output_tokens: reasoning,
      total_tokens: total
    }
  };
}
function parseDeviceSubscription(raw) {
  if (!raw || typeof raw !== "object") return null;
  const tool = normalizeTextField(raw.tool, { lowerCase: true, maxLen: 64 });
  const provider = normalizeTextField(raw.provider, { lowerCase: true, maxLen: 64 });
  const product = normalizeTextField(raw.product, { lowerCase: true, maxLen: 64 });
  const planType = normalizeTextField(raw.plan_type ?? raw.planType, {
    lowerCase: true,
    maxLen: 64
  });
  if (!tool || !provider || !product || !planType) return null;
  return {
    tool,
    provider,
    product,
    plan_type: planType,
    rate_limit_tier: normalizeTextField(raw.rate_limit_tier ?? raw.rateLimitTier, {
      lowerCase: true,
      maxLen: 128
    }),
    active_start: normalizeIsoField(raw.active_start ?? raw.activeStart),
    active_until: normalizeIsoField(raw.active_until ?? raw.activeUntil),
    last_checked: normalizeIsoField(raw.last_checked ?? raw.lastChecked)
  };
}
function buildRows({ hourly, tokenRow, nowIso, billableRuleVersion = BILLABLE_RULE_VERSION }) {
  const byHour = /* @__PURE__ */ new Map();
  for (const raw of hourly) {
    const parsed = parseHourlyBucket(raw);
    if (!parsed.ok) return { error: parsed.error, data: [] };
    const source = parsed.value.source || "codex";
    const model = parsed.value.model || DEFAULT_MODEL2;
    const dedupeKey = `${parsed.value.hour_start}::${source}::${model}`;
    byHour.set(dedupeKey, { ...parsed.value, source, model });
  }
  const rows = [];
  for (const bucket of byHour.values()) {
    const billable = computeBillableTotalTokens2({ source: bucket.source, totals: bucket });
    rows.push({
      user_id: tokenRow.user_id,
      device_id: tokenRow.device_id,
      device_token_id: tokenRow.id,
      source: bucket.source,
      model: bucket.model,
      hour_start: bucket.hour_start,
      input_tokens: bucket.input_tokens,
      cached_input_tokens: bucket.cached_input_tokens,
      output_tokens: bucket.output_tokens,
      reasoning_output_tokens: bucket.reasoning_output_tokens,
      total_tokens: bucket.total_tokens,
      billable_total_tokens: billable.toString(),
      billable_rule_version: billableRuleVersion,
      updated_at: nowIso
    });
  }
  return { error: null, data: rows };
}
function buildProjectRows({ hourly, tokenRow, nowIso }) {
  const byHour = /* @__PURE__ */ new Map();
  for (const raw of hourly) {
    const parsed = parseProjectHourlyBucket(raw);
    if (!parsed.ok) return { error: parsed.error, data: [] };
    const source = parsed.value.source || "codex";
    const dedupeKey = `${parsed.value.hour_start}::${source}::${parsed.value.project_key}`;
    byHour.set(dedupeKey, { ...parsed.value, source });
  }
  const rows = [];
  for (const bucket of byHour.values()) {
    const billable = computeBillableTotalTokens2({ source: bucket.source, totals: bucket });
    rows.push({
      user_id: tokenRow.user_id,
      device_id: tokenRow.device_id,
      device_token_id: tokenRow.id,
      source: bucket.source,
      project_key: bucket.project_key,
      project_ref: bucket.project_ref,
      hour_start: bucket.hour_start,
      input_tokens: bucket.input_tokens,
      cached_input_tokens: bucket.cached_input_tokens,
      output_tokens: bucket.output_tokens,
      reasoning_output_tokens: bucket.reasoning_output_tokens,
      total_tokens: bucket.total_tokens,
      billable_total_tokens: billable.toString(),
      billable_rule_version: BILLABLE_RULE_VERSION,
      updated_at: nowIso
    });
  }
  return { error: null, data: rows };
}
function buildSubscriptionRows({ subscriptions, tokenRow, nowIso }) {
  const deduped = /* @__PURE__ */ new Map();
  for (const raw of subscriptions) {
    const parsed = parseDeviceSubscription(raw);
    if (!parsed) continue;
    const key = `${parsed.tool}::${parsed.provider}::${parsed.product}`;
    deduped.set(key, parsed);
  }
  const rows = [];
  for (const subscription of deduped.values()) {
    rows.push({
      user_id: tokenRow.user_id,
      device_id: tokenRow.device_id,
      device_token_id: tokenRow.id,
      tool: subscription.tool,
      provider: subscription.provider,
      product: subscription.product,
      plan_type: subscription.plan_type,
      rate_limit_tier: subscription.rate_limit_tier,
      active_start: subscription.active_start,
      active_until: subscription.active_until,
      last_checked: subscription.last_checked,
      observed_at: nowIso,
      updated_at: nowIso
    });
  }
  return { error: null, data: rows };
}
function deriveMetricsSource(rows) {
  if (!Array.isArray(rows) || rows.length === 0) return null;
  const sources = /* @__PURE__ */ new Set();
  for (const row of rows) {
    const source = typeof row?.source === "string" ? row.source.trim() : "";
    if (source) sources.add(source);
  }
  if (sources.size === 1) return Array.from(sources)[0];
  if (sources.size > 1) return "mixed";
  return null;
}
if (!globalThis[CORE_KEY12]) {
  Object.defineProperty(globalThis, CORE_KEY12, {
    value: {
      BILLABLE_RULE_VERSION,
      DEFAULT_MODEL: DEFAULT_MODEL2,
      buildProjectRows,
      buildRows,
      buildSubscriptionRows,
      deriveMetricsSource,
      normalizeDeviceSubscriptionsPayload,
      normalizeHourlyPayload,
      normalizeProjectHourlyPayload,
      parseDeviceSubscription,
      parseHourlyBucket,
      parseProjectHourlyBucket,
      parseUtcHalfHourStart,
      toNonNegativeInt
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/shared/db/records.mjs
var CORE_KEY13 = "__vibeusageDbRecordsCore";
function buildAuthHeaders({ anonKey, tokenHash }) {
  return {
    apikey: anonKey,
    Authorization: `Bearer ${anonKey}`,
    "x-vibeusage-device-token-hash": tokenHash
  };
}
async function readApiJson(res) {
  const text = await res.text();
  if (!text) return { data: null, error: null, code: null };
  try {
    const parsed = JSON.parse(text);
    return {
      data: parsed,
      error: parsed?.message || parsed?.error || null,
      code: parsed?.code || null
    };
  } catch (_error) {
    return { data: null, error: text.slice(0, 300), code: null };
  }
}
function normalizeRows(data) {
  if (Array.isArray(data)) return data;
  if (data && typeof data === "object" && Array.isArray(data.data)) return data.data;
  return null;
}
function isUpsertUnsupported(result) {
  const status = Number(result?.status || 0);
  if (status !== 400 && status !== 404 && status !== 405 && status !== 409 && status !== 422) {
    return false;
  }
  const msg = String(result?.error || "").toLowerCase();
  if (!msg) return false;
  return msg.includes("on_conflict") || msg.includes("resolution") || msg.includes("prefer") || msg.includes("unknown") || msg.includes("invalid");
}
async function recordsUpsert({
  url,
  anonKey,
  tokenHash,
  rows,
  onConflict,
  prefer,
  resolution,
  select,
  fetcher
}) {
  const target = new URL(url.toString());
  if (onConflict) target.searchParams.set("on_conflict", onConflict);
  if (select) target.searchParams.set("select", select);
  const preferParts = [];
  if (prefer) preferParts.push(prefer);
  if (resolution) preferParts.push(`resolution=${resolution}`);
  const preferHeader = preferParts.filter(Boolean).join(",");
  const res = await (fetcher || fetch)(target.toString(), {
    method: "POST",
    headers: {
      ...buildAuthHeaders({ anonKey, tokenHash }),
      ...preferHeader ? { Prefer: preferHeader } : {},
      "Content-Type": "application/json"
    },
    body: JSON.stringify(rows)
  });
  const { data, error, code } = await readApiJson(res);
  return { ok: res.ok, status: res.status, data, error, code };
}
if (!globalThis[CORE_KEY13]) {
  Object.defineProperty(globalThis, CORE_KEY13, {
    value: {
      buildAuthHeaders,
      isUpsertUnsupported,
      normalizeRows,
      readApiJson,
      recordsUpsert
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/shared/db/ingest.mjs
var CORE_KEY14 = "__vibeusageIngestDbCore";
var DEVICE_TOKEN_SELECT = "id,user_id,device_id,revoked_at,last_sync_at";
var dateCore2 = globalThis.__vibeusageDateCore;
if (!dateCore2) throw new Error("date core not initialized");
var { isWithinInterval: isWithinInterval2, normalizeIso: normalizeIso3 } = dateCore2;
function toNonNegativeInt2(value) {
  if (typeof value !== "number") return 0;
  if (!Number.isFinite(value)) return 0;
  if (!Number.isInteger(value)) return 0;
  if (value < 0) return 0;
  return value;
}
async function fetchDeviceTokenRow({ serviceClient, baseUrl, anonKey, tokenHash, fetcher }) {
  if (serviceClient?.database?.from) {
    const { data: tokenRow2, error: error2 } = await serviceClient.database.from("vibeusage_tracker_device_tokens").select(DEVICE_TOKEN_SELECT).eq("token_hash", tokenHash).maybeSingle();
    if (error2) throw new Error(error2.message);
    if (!tokenRow2 || tokenRow2.revoked_at) return null;
    return tokenRow2;
  }
  if (!baseUrl || !anonKey) throw new Error("Anon key missing");
  const url = new URL("/api/database/records/vibeusage_tracker_device_tokens", baseUrl);
  url.searchParams.set("select", DEVICE_TOKEN_SELECT);
  url.searchParams.set("token_hash", `eq.${tokenHash}`);
  url.searchParams.set("limit", "1");
  const res = await (fetcher || fetch)(url.toString(), {
    method: "GET",
    headers: buildAuthHeaders({ anonKey, tokenHash })
  });
  const { data, error } = await readApiJson(res);
  if (!res.ok) throw new Error(error || `HTTP ${res.status}`);
  const rows = normalizeRows(data);
  const tokenRow = rows?.[0] || null;
  if (!tokenRow || tokenRow.revoked_at) return null;
  return tokenRow;
}
async function updateRecord({ baseUrl, anonKey, tokenHash, table, match, values, fetcher }) {
  const url = new URL(`/api/database/records/${table}`, baseUrl);
  for (const [key, val] of Object.entries(match || {})) {
    url.searchParams.set(key, `eq.${val}`);
  }
  const res = await (fetcher || fetch)(url.toString(), {
    method: "PATCH",
    headers: {
      ...buildAuthHeaders({ anonKey, tokenHash }),
      "Content-Type": "application/json"
    },
    body: JSON.stringify(values)
  });
  const { data, error, code } = await readApiJson(res);
  return { ok: res.ok, status: res.status, data, error, code };
}
async function touchDeviceTokenAndDevice({
  serviceClient,
  baseUrl,
  anonKey,
  tokenHash,
  tokenRow,
  nowIso,
  fetcher,
  minIntervalMinutes = 30
}) {
  if (!tokenRow) return;
  const lastSyncAt = normalizeIso3(tokenRow.last_sync_at);
  const shouldUpdateSync = !lastSyncAt || !isWithinInterval2(lastSyncAt, minIntervalMinutes, nowIso);
  const tokenUpdate = shouldUpdateSync ? { last_used_at: nowIso, last_sync_at: nowIso } : { last_used_at: nowIso };
  try {
    if (serviceClient?.database?.from) {
      await serviceClient.database.from("vibeusage_tracker_device_tokens").update(tokenUpdate).eq("id", tokenRow.id);
    } else if (baseUrl && anonKey) {
      await updateRecord({
        baseUrl,
        anonKey,
        tokenHash,
        table: "vibeusage_tracker_device_tokens",
        match: { id: tokenRow.id },
        values: tokenUpdate,
        fetcher
      });
    }
  } catch (_error) {
  }
  try {
    if (serviceClient?.database?.from) {
      await serviceClient.database.from("vibeusage_tracker_devices").update({ last_seen_at: nowIso }).eq("id", tokenRow.device_id);
    } else if (baseUrl && anonKey) {
      await updateRecord({
        baseUrl,
        anonKey,
        tokenHash,
        table: "vibeusage_tracker_devices",
        match: { id: tokenRow.device_id },
        values: { last_seen_at: nowIso },
        fetcher
      });
    }
  } catch (_error) {
  }
}
async function upsertHourlyUsage({
  serviceClient,
  baseUrl,
  serviceRoleKey,
  anonKey,
  tokenHash,
  tokenRow,
  rows,
  nowIso,
  fetcher
}) {
  if (serviceClient && serviceRoleKey && baseUrl) {
    const url2 = new URL("/api/database/records/vibeusage_tracker_hourly", baseUrl);
    const res2 = await recordsUpsert({
      url: url2,
      anonKey: serviceRoleKey,
      tokenHash,
      rows,
      onConflict: "user_id,device_id,source,model,hour_start",
      prefer: "return=representation",
      resolution: "merge-duplicates",
      select: "hour_start",
      fetcher
    });
    if (res2.ok) {
      const insertedRows = normalizeRows(res2.data);
      const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
      await touchDeviceTokenAndDevice({ serviceClient, tokenRow, nowIso });
      return { ok: true, inserted, skipped: 0 };
    }
    if (!isUpsertUnsupported(res2)) {
      return { ok: false, error: res2.error || `HTTP ${res2.status}`, inserted: 0, skipped: 0 };
    }
  }
  if (serviceClient?.database?.from) {
    const { error } = await serviceClient.database.from("vibeusage_tracker_hourly").upsert(rows, { onConflict: "user_id,device_id,source,model,hour_start" });
    if (error) return { ok: false, error: error.message, inserted: 0, skipped: 0 };
    await touchDeviceTokenAndDevice({ serviceClient, tokenRow, nowIso });
    return { ok: true, inserted: rows.length, skipped: 0 };
  }
  if (!anonKey || !baseUrl) {
    return { ok: false, error: "Anon key missing", inserted: 0, skipped: 0 };
  }
  const url = new URL("/api/database/records/vibeusage_tracker_hourly", baseUrl);
  const res = await recordsUpsert({
    url,
    anonKey,
    tokenHash,
    rows,
    onConflict: "user_id,device_id,source,model,hour_start",
    prefer: "return=representation",
    resolution: "merge-duplicates",
    select: "hour_start",
    fetcher
  });
  if (res.ok) {
    const insertedRows = normalizeRows(res.data);
    const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
    await touchDeviceTokenAndDevice({ baseUrl, anonKey, tokenHash, tokenRow, nowIso, fetcher });
    return { ok: true, inserted, skipped: 0 };
  }
  if (isUpsertUnsupported(res)) {
    return {
      ok: false,
      error: res.error || "Half-hour upsert unsupported",
      inserted: 0,
      skipped: 0
    };
  }
  return { ok: false, error: res.error || `HTTP ${res.status}`, inserted: 0, skipped: 0 };
}
async function upsertProjectUsage({
  serviceClient,
  baseUrl,
  serviceRoleKey,
  anonKey,
  tokenHash,
  tokenRow,
  rows,
  nowIso,
  fetcher
}) {
  if (serviceClient && serviceRoleKey && baseUrl) {
    const url2 = new URL("/api/database/records/vibeusage_project_usage_hourly", baseUrl);
    const res2 = await recordsUpsert({
      url: url2,
      anonKey: serviceRoleKey,
      tokenHash,
      rows,
      onConflict: "user_id,project_key,hour_start,source",
      prefer: "return=representation",
      resolution: "merge-duplicates",
      select: "hour_start",
      fetcher
    });
    if (res2.ok) {
      const insertedRows = normalizeRows(res2.data);
      const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
      await touchDeviceTokenAndDevice({ serviceClient, tokenRow, nowIso });
      return { ok: true, inserted, skipped: 0 };
    }
    if (!isUpsertUnsupported(res2)) {
      return { ok: false, error: res2.error || `HTTP ${res2.status}`, inserted: 0, skipped: 0 };
    }
  }
  if (serviceClient?.database?.from) {
    const { error } = await serviceClient.database.from("vibeusage_project_usage_hourly").upsert(rows, { onConflict: "user_id,project_key,hour_start,source" });
    if (error) return { ok: false, error: error.message, inserted: 0, skipped: 0 };
    await touchDeviceTokenAndDevice({ serviceClient, tokenRow, nowIso });
    return { ok: true, inserted: rows.length, skipped: 0 };
  }
  if (!anonKey || !baseUrl) {
    return { ok: false, error: "Anon key missing", inserted: 0, skipped: 0 };
  }
  const url = new URL("/api/database/records/vibeusage_project_usage_hourly", baseUrl);
  const res = await recordsUpsert({
    url,
    anonKey,
    tokenHash,
    rows,
    onConflict: "user_id,project_key,hour_start,source",
    prefer: "return=representation",
    resolution: "merge-duplicates",
    select: "hour_start",
    fetcher
  });
  if (res.ok) {
    const insertedRows = normalizeRows(res.data);
    const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
    await touchDeviceTokenAndDevice({ baseUrl, anonKey, tokenHash, tokenRow, nowIso, fetcher });
    return { ok: true, inserted, skipped: 0 };
  }
  if (isUpsertUnsupported(res)) {
    return {
      ok: false,
      error: res.error || "Half-hour upsert unsupported",
      inserted: 0,
      skipped: 0
    };
  }
  return { ok: false, error: res.error || `HTTP ${res.status}`, inserted: 0, skipped: 0 };
}
async function upsertProjectRegistry({
  serviceClient,
  baseUrl,
  serviceRoleKey,
  anonKey,
  tokenHash,
  rows,
  fetcher
}) {
  if (serviceClient && serviceRoleKey && baseUrl) {
    const url2 = new URL("/api/database/records/vibeusage_projects", baseUrl);
    const res2 = await recordsUpsert({
      url: url2,
      anonKey: serviceRoleKey,
      tokenHash,
      rows,
      onConflict: "user_id,project_key",
      prefer: "return=representation",
      resolution: "merge-duplicates",
      select: "project_key",
      fetcher
    });
    if (res2.ok) {
      const insertedRows = normalizeRows(res2.data);
      const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
      return { ok: true, inserted, skipped: 0 };
    }
    if (!isUpsertUnsupported(res2)) {
      return { ok: false, error: res2.error || `HTTP ${res2.status}`, inserted: 0, skipped: 0 };
    }
  }
  if (serviceClient?.database?.from) {
    const { error } = await serviceClient.database.from("vibeusage_projects").upsert(rows, { onConflict: "user_id,project_key" });
    if (error) return { ok: false, error: error.message, inserted: 0, skipped: 0 };
    return { ok: true, inserted: rows.length, skipped: 0 };
  }
  if (!anonKey || !baseUrl) {
    return { ok: false, error: "Anon key missing", inserted: 0, skipped: 0 };
  }
  const url = new URL("/api/database/records/vibeusage_projects", baseUrl);
  const res = await recordsUpsert({
    url,
    anonKey,
    tokenHash,
    rows,
    onConflict: "user_id,project_key",
    prefer: "return=representation",
    resolution: "merge-duplicates",
    select: "project_key",
    fetcher
  });
  if (res.ok) {
    const insertedRows = normalizeRows(res.data);
    const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
    return { ok: true, inserted, skipped: 0 };
  }
  if (isUpsertUnsupported(res)) {
    return { ok: false, error: res.error || "Project upsert unsupported", inserted: 0, skipped: 0 };
  }
  return { ok: false, error: res.error || `HTTP ${res.status}`, inserted: 0, skipped: 0 };
}
async function upsertDeviceSubscriptions({
  serviceClient,
  baseUrl,
  serviceRoleKey,
  anonKey,
  tokenHash,
  rows,
  fetcher
}) {
  if (!Array.isArray(rows) || rows.length === 0) {
    return { ok: true, inserted: 0, skipped: 0 };
  }
  if (serviceClient && serviceRoleKey && baseUrl) {
    const url2 = new URL("/api/database/records/vibeusage_tracker_subscriptions", baseUrl);
    const res2 = await recordsUpsert({
      url: url2,
      anonKey: serviceRoleKey,
      tokenHash,
      rows,
      onConflict: "user_id,tool,provider,product",
      prefer: "return=representation",
      resolution: "merge-duplicates",
      select: "tool,provider,product",
      fetcher
    });
    if (res2.ok) {
      const insertedRows = normalizeRows(res2.data);
      const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
      return { ok: true, inserted, skipped: 0 };
    }
    if (!isUpsertUnsupported(res2)) {
      return { ok: false, error: res2.error || `HTTP ${res2.status}`, inserted: 0, skipped: 0 };
    }
  }
  if (serviceClient?.database?.from) {
    const { error } = await serviceClient.database.from("vibeusage_tracker_subscriptions").upsert(rows, { onConflict: "user_id,tool,provider,product" });
    if (error) return { ok: false, error: error.message, inserted: 0, skipped: 0 };
    return { ok: true, inserted: rows.length, skipped: 0 };
  }
  if (!anonKey || !baseUrl) {
    return { ok: false, error: "Anon key missing", inserted: 0, skipped: 0 };
  }
  const url = new URL("/api/database/records/vibeusage_tracker_subscriptions", baseUrl);
  const res = await recordsUpsert({
    url,
    anonKey,
    tokenHash,
    rows,
    onConflict: "user_id,tool,provider,product",
    prefer: "return=representation",
    resolution: "merge-duplicates",
    select: "tool,provider,product",
    fetcher
  });
  if (res.ok) {
    const insertedRows = normalizeRows(res.data);
    const inserted = Array.isArray(insertedRows) ? insertedRows.length : rows.length;
    return { ok: true, inserted, skipped: 0 };
  }
  if (isUpsertUnsupported(res)) {
    return {
      ok: false,
      error: res.error || "Subscriptions upsert unsupported",
      inserted: 0,
      skipped: 0
    };
  }
  return { ok: false, error: res.error || `HTTP ${res.status}`, inserted: 0, skipped: 0 };
}
async function recordIngestBatchMetrics({
  serviceClient,
  baseUrl,
  anonKey,
  tokenHash,
  tokenRow,
  bucketCount,
  inserted,
  skipped,
  source,
  fetcher
}) {
  if (!tokenRow) return;
  const row = {
    user_id: tokenRow.user_id,
    device_id: tokenRow.device_id,
    device_token_id: tokenRow.id,
    source: typeof source === "string" ? source : null,
    bucket_count: toNonNegativeInt2(bucketCount),
    inserted: toNonNegativeInt2(inserted),
    skipped: toNonNegativeInt2(skipped)
  };
  try {
    if (serviceClient?.database?.from) {
      const { error } = await serviceClient.database.from("vibeusage_tracker_ingest_batches").insert(row);
      if (error) throw new Error(error.message);
      return;
    }
    if (!anonKey || !baseUrl) return;
    const url = new URL("/api/database/records/vibeusage_tracker_ingest_batches", baseUrl);
    const res = await (fetcher || fetch)(url.toString(), {
      method: "POST",
      headers: {
        ...buildAuthHeaders({ anonKey, tokenHash }),
        "Content-Type": "application/json"
      },
      body: JSON.stringify(row)
    });
    if (!res.ok) {
      const { error } = await readApiJson(res);
      throw new Error(error || `HTTP ${res.status}`);
    }
  } catch (_error) {
  }
}
if (!globalThis[CORE_KEY14]) {
  Object.defineProperty(globalThis, CORE_KEY14, {
    value: {
      fetchDeviceTokenRow,
      recordIngestBatchMetrics,
      touchDeviceTokenAndDevice,
      upsertDeviceSubscriptions,
      upsertHourlyUsage,
      upsertProjectRegistry,
      upsertProjectUsage
    },
    configurable: true,
    enumerable: false,
    writable: false
  });
}

// insforge-src/functions-esm/vibeusage-ingest.js
var MAX_BUCKETS = 500;
var MAX_DEVICE_SUBSCRIPTIONS = 16;
var ingestGuard = createConcurrencyGuard({
  name: "vibeusage-ingest",
  envKey: ["VIBEUSAGE_INGEST_MAX_INFLIGHT"],
  defaultMax: 0,
  retryAfterEnvKey: ["VIBEUSAGE_INGEST_RETRY_AFTER_MS"],
  defaultRetryAfterMs: 1e3
});
var vibeusage_ingest_default = withRequestLogging2("vibeusage-ingest", async function(request, logger) {
  const opt = handleOptions2(request);
  if (opt) return opt;
  const methodErr = requireMethod2(request, "POST");
  if (methodErr) return methodErr;
  const deviceToken = getBearerToken2(request.headers.get("Authorization"));
  if (!deviceToken) return json2({ error: "Missing bearer token" }, 401);
  const guard = ingestGuard?.acquire();
  if (guard && !guard.ok) {
    return json2({ error: "Too many requests" }, 429, guard.headers);
  }
  const fetcher = logger?.fetch || fetch;
  const baseUrl = getBaseUrl2();
  const serviceRoleKey = getServiceRoleKey2();
  const anonKey = getAnonKey2();
  const serviceClient = serviceRoleKey ? await createEdgeClient({
    baseUrl,
    anonKey: anonKey || serviceRoleKey,
    edgeFunctionToken: serviceRoleKey
  }) : null;
  try {
    const tokenHash = await sha256Hex2(deviceToken);
    let tokenRow = null;
    try {
      tokenRow = await fetchDeviceTokenRow({ serviceClient, baseUrl, anonKey, tokenHash, fetcher });
    } catch (error) {
      return json2({ error: error?.message || "Internal error" }, 500);
    }
    if (!tokenRow) return json2({ error: "Unauthorized" }, 401);
    const body = await readJson2(request);
    if (body.error) return json2({ error: body.error }, body.status);
    const hourly = normalizeHourlyPayload(body.data);
    const projectHourly = normalizeProjectHourlyPayload(body.data);
    const deviceSubscriptions = normalizeDeviceSubscriptionsPayload(body.data);
    if (!Array.isArray(hourly) && !Array.isArray(projectHourly)) {
      return json2({ error: "Invalid payload: expected {hourly:[...]} or [...]" }, 400);
    }
    if (Array.isArray(hourly) && hourly.length > MAX_BUCKETS) {
      return json2({ error: `Too many buckets (max ${MAX_BUCKETS})` }, 413);
    }
    if (Array.isArray(projectHourly) && projectHourly.length > MAX_BUCKETS) {
      return json2({ error: `Too many buckets (max ${MAX_BUCKETS})` }, 413);
    }
    if (Array.isArray(deviceSubscriptions) && deviceSubscriptions.length > MAX_DEVICE_SUBSCRIPTIONS) {
      return json2(
        { error: `Too many device subscriptions (max ${MAX_DEVICE_SUBSCRIPTIONS})` },
        413
      );
    }
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const rows = Array.isArray(hourly) ? buildRows({ hourly, tokenRow, nowIso, billableRuleVersion: BILLABLE_RULE_VERSION }) : { error: null, data: [] };
    if (rows.error) return json2({ error: rows.error }, 400);
    const projectRows = Array.isArray(projectHourly) ? buildProjectRows({ hourly: projectHourly, tokenRow, nowIso }) : { error: null, data: [] };
    if (projectRows.error) return json2({ error: projectRows.error }, 400);
    const subscriptionRows = Array.isArray(deviceSubscriptions) ? buildSubscriptionRows({ subscriptions: deviceSubscriptions, tokenRow, nowIso }) : { error: null, data: [] };
    if (subscriptionRows.error) return json2({ error: subscriptionRows.error }, 400);
    let projectInserted = 0;
    let projectSkipped = 0;
    if (projectRows.data.length > 0) {
      const registryByKey = /* @__PURE__ */ new Map();
      for (const row of projectRows.data) {
        registryByKey.set(row.project_key, {
          user_id: row.user_id,
          device_id: row.device_id,
          device_token_id: row.device_token_id,
          source: row.source,
          project_key: row.project_key,
          project_ref: row.project_ref,
          last_seen_at: nowIso,
          updated_at: nowIso
        });
      }
      const registryRows = Array.from(registryByKey.values());
      const registryUpsert = await upsertProjectRegistry({
        serviceClient,
        baseUrl,
        serviceRoleKey,
        anonKey,
        tokenHash,
        rows: registryRows,
        fetcher
      });
      if (!registryUpsert.ok) return json2({ error: registryUpsert.error }, 500);
      const projectUpsert = await upsertProjectUsage({
        serviceClient,
        baseUrl,
        serviceRoleKey,
        anonKey,
        tokenHash,
        tokenRow,
        rows: projectRows.data,
        nowIso,
        fetcher
      });
      if (!projectUpsert.ok) return json2({ error: projectUpsert.error }, 500);
      projectInserted = projectUpsert.inserted;
      projectSkipped = projectUpsert.skipped;
    }
    if (subscriptionRows.data.length > 0) {
      const subscriptionUpsert = await upsertDeviceSubscriptions({
        serviceClient,
        baseUrl,
        serviceRoleKey,
        anonKey,
        tokenHash,
        rows: subscriptionRows.data,
        fetcher
      });
      if (!subscriptionUpsert.ok) {
        logger?.log?.({
          stage: "subscription_upsert_failed",
          status: 200,
          errorCode: "SUBSCRIPTION_UPSERT_FAILED",
          details: subscriptionUpsert.error
        });
      }
    }
    if (rows.data.length === 0) {
      await recordIngestBatchMetrics({
        serviceClient,
        baseUrl,
        anonKey,
        tokenHash,
        tokenRow,
        bucketCount: 0,
        inserted: 0,
        skipped: 0,
        source: null,
        fetcher
      });
      return json2(
        {
          success: true,
          inserted: 0,
          skipped: 0,
          project_inserted: projectInserted,
          project_skipped: projectSkipped
        },
        200
      );
    }
    const upsert = await upsertHourlyUsage({
      serviceClient,
      baseUrl,
      serviceRoleKey,
      anonKey,
      tokenHash,
      tokenRow,
      rows: rows.data,
      nowIso,
      fetcher
    });
    if (!upsert.ok) return json2({ error: upsert.error }, 500);
    await recordIngestBatchMetrics({
      serviceClient,
      baseUrl,
      anonKey,
      tokenHash,
      tokenRow,
      bucketCount: rows.data.length,
      inserted: upsert.inserted,
      skipped: upsert.skipped,
      source: deriveMetricsSource(rows.data),
      fetcher
    });
    return json2(
      {
        success: true,
        inserted: upsert.inserted,
        skipped: upsert.skipped,
        project_inserted: projectInserted,
        project_skipped: projectSkipped
      },
      200
    );
  } finally {
    if (guard && typeof guard.release === "function") guard.release();
  }
});
export {
  vibeusage_ingest_default as default
};
