# VIBEUSAGE_HERMES_PLUGIN
# Generated by VibeUsage. Do not edit manually.
import json
import os
from datetime import datetime, timezone

LEDGER_PATH = "__LEDGER_PATH__"
SOURCE = "hermes"
VERSION = 1


def _iso_now():
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _safe_int(value):
    try:
        return max(0, int(value or 0))
    except Exception:
        return 0


def _append_record(record):
    try:
        os.makedirs(os.path.dirname(LEDGER_PATH), exist_ok=True)
        with open(LEDGER_PATH, "a", encoding="utf-8") as handle:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")
    except Exception:
        return None
    return None


def _base_record(record_type, session_id="", platform="", model="", provider=""):
    return {
        "version": VERSION,
        "type": str(record_type or ""),
        "source": SOURCE,
        "session_id": str(session_id or ""),
        "platform": str(platform or ""),
        "model": str(model or ""),
        "provider": str(provider or ""),
        "emitted_at": _iso_now(),
    }


def on_session_start(session_id="", model="", platform="", **_kwargs):
    return _append_record(_base_record("session_start", session_id=session_id, platform=platform, model=model))


def post_api_request(session_id="", platform="", model="", provider="", api_mode="", api_call_count=0, finish_reason="", usage=None, **_kwargs):
    if not isinstance(usage, dict):
        return None
    record = _base_record("usage", session_id=session_id, platform=platform, model=model, provider=provider)
    record.update({
        "api_mode": str(api_mode or ""),
        "api_call_count": _safe_int(api_call_count),
        "input_tokens": _safe_int(usage.get("input_tokens")),
        "output_tokens": _safe_int(usage.get("output_tokens")),
        "cache_read_tokens": _safe_int(usage.get("cache_read_tokens")),
        "cache_write_tokens": _safe_int(usage.get("cache_write_tokens")),
        "reasoning_tokens": _safe_int(usage.get("reasoning_tokens")),
        "total_tokens": _safe_int(usage.get("total_tokens")),
        "finish_reason": str(finish_reason or ""),
    })
    return _append_record(record)


def on_session_end(session_id="", model="", platform="", **_kwargs):
    return _append_record(_base_record("session_end", session_id=session_id, platform=platform, model=model))


def register(ctx):
    ctx.register_hook("on_session_start", on_session_start)
    ctx.register_hook("post_api_request", post_api_request)
    ctx.register_hook("on_session_end", on_session_end)
